### ISSUE TITLE
Support for TF 0.12

### ISSUE THREAD

**Issue by kirubakaran25** [terraform-aws-modules/terraform-aws-alb#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Versions [e.g. terraform version, kitchen-terraform version, module version, etc.]

**Additional context**

**Comment by geowa4** [comment]
Duplicate of #105?

**Comment by antonbabenko** [comment]
Yes, and I am very well aware of this already. :)

Hopefully to release it tomorrow or the next day.
