### ISSUE TITLE
Additional flexibility for custom endpoints

### ISSUE THREAD

**Issue by rslocum** [terraform-aws-modules/terraform-aws-alb#109]
While calling custom endpoints is allowed, it does this at the provider level, which means you need to instantiate multiple providers if you are using multiple endpoints based on the resource

It would be nice to have an optional field that could pass a custom endpoint at the resource level. e.g. we need a fips alb, but the rest of the albs in the environment do not need that level of restrictiveness. Currently we would need to have multiple providers, or create the alb via the cli and import it in.

**Comment by antonbabenko** [comment]
Hi @rslocum !

I think you are overengineering something if you would want to have this feature. The way most of Terraform modules you see in the public (including [terraform-aws-modules](https://github.com/terraform-aws-modules)) is that they inherit default `aws` provider and use it.

There is seldom a need to specify it as an argument to a module (using `providers { aws = "aws.my-secondary-provider" }`) and almost never as an argument to individual resources inside of the module.

If you need to create resources with different AWS provider configurations you need to invoke this module multiple times.

This module will not be extended to support custom provider blocks on a resource level.
