### ISSUE TITLE
Unable to use conditional expression to set value of create_alb

### ISSUE THREAD

**Issue by ahjr** [terraform-aws-modules/terraform-aws-alb#110]
**Describe the bug**
Unable to use a ternary conditional expression to determine the value of create_alb

**To Reproduce**
1. Add `create_alb = "${local.some_var=="some val"?true:false}"` to alb definition

**Expected behavior**
ALB to be created or not based on the interpolated value

**Desktop (please complete the following information):**
 - OS: Amazon Linux
 - Versions terraform v0.11.14, aws-alb v3.6.0

**Additional context**
These are the errors I get but I don't think they're particularly helpful:

> Error: module.swarm-alb.aws_lb_listener.frontend_http_tcp: 1 error occurred:
>   * module.swarm-alb.aws_lb_listener.frontend_http_tcp: At column 32, line 1: list "var.http_tcp_listeners" does not have any elements so cannot determine type. in:
> 
> ${lookup(var.http_tcp_listeners[count.index], "port")}
> 
> Error: module.swarm-alb.aws_lb_listener_certificate.https_listener: 1 error occurred:
>   * module.swarm-alb.aws_lb_listener_certificate.https_listener: At column 29, line 1: list "var.extra_ssl_certs" does not have any elements so cannot determine type. in:
> 
> ${lookup(var.extra_ssl_certs[count.index], "certificate_arn")}
> 
> Error: module.swarm-alb.aws_lb_listener.frontend_http_tcp_no_logs: 1 error occurred:
>   * module.swarm-alb.aws_lb_listener.frontend_http_tcp_no_logs: At column 70, line 1: list "var.http_tcp_listeners" does not have any elements so cannot determine type. in:
> 
> ${aws_lb_target_group.main_no_logs.*.id[lookup(var.http_tcp_listeners[count.index], "target_group_index", 0)]}
> 
> Error: module.swarm-alb.aws_lb_listener_certificate.https_listener_no_logs: 1 error occurred:
>   * module.swarm-alb.aws_lb_listener_certificate.https_listener_no_logs: At column 29, line 1: list "var.extra_ssl_certs" does not have any elements so cannot determine type. in:
> 
> ${lookup(var.extra_ssl_certs[count.index], "certificate_arn")}
>

**Comment by ahjr** [comment]
Changing values to `true` or `false` or `"true"` or `"false"` works as expected, but hard coding the value isn't going to work for my use case.

**Comment by antonbabenko** [comment]
Hi @ahjr !

Terraform 0.11 and this module version prior [v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) is not going to be supported.

Please upgrade your code to support Terraform 0.12 where this issue is fixed.

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.
