### ISSUE TITLE
Change Logging_enabled default to false

### ISSUE THREAD

**Issue by snorberhuis** [terraform-aws-modules/terraform-aws-alb#112]
**Describe the bug**
The readme states that `log_bucket_name` and  `log_location_prefix` are not required. Using a module with only the required parameters, these parameters are required as `logging_enabled` is set to true as default. Applying would result in an error in this state.

```
Error: Failure configuring LB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
	status code: 400, request id: 27420ad0-bd00-11e9-9575-1d4789fd3dae
```

**To Reproduce**
1. Use the module with only required parameters.
2. Apply the module

**Expected behavior**
If I fill in all required parameters, I would expect the module to apply.

**Desktop (please complete the following information):**
 - OS: OSX
 - Versions terraform 0.12.4, module version 4.1.0

**Additional context**
I can make a PR for it.

**Comment by antonbabenko** [comment]
Please check out [v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) which has been just released, where this issue has been reworked.

Also, check the source of [examples/complete-alb](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf) for more details.

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.
