### ISSUE TITLE
target_groups optional param is not optional

### ISSUE THREAD

**Issue by vide** [terraform-aws-modules/terraform-aws-alb#116]
**Describe the bug**
the `target_group` param is listed as optional but if you don't pass it then the module will always fail with

```
Error: Invalid index

  on .terraform/modules/alb/terraform-aws-modules-terraform-aws-alb-61e7316/alb_no_logs.tf line 130, in resource "aws_lb_listener" "frontend_http_tcp_no_logs":
 130:     target_group_arn = aws_lb_target_group.main_no_logs[lookup(var.http_tcp_listeners[count.index], "target_group_index", 0)].id
    |----------------
    | aws_lb_target_group.main_no_logs is empty tuple
    | count.index is 0
    | var.http_tcp_listeners is list of map of string with 1 element

The given key does not identify an element in this collection value.

```

because the `count`on this resource doesn't check for the `target_group` length, only for `var.create_alb` and it always tries to add a TG in the `default_action{}` of the `aws_lb_listener`

This applies to the log enabled version of the ALB too

**Desktop (please complete the following information):**
 - OS: Linux
 - Terraform 0.12.8 and terrafor-aws-alb 4.1.0

**Additional context**
I can open a PR to try to fix this but the best solution is not that clear to me. A `default_action{}` must be provided for any listener so it should be either a TG or some of the new targets ALB now permits (like a fixed response). WDYT?

**Comment by antonbabenko** [comment]
You are right, you need to specify `target_group_index = 0` (or other value).

Please check out [v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) which has been just released, where this issue has been reworked.

Also, check the source of [examples/complete-alb](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf) for more details.

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.

PS: Making other types of `default_action` is still not supported, it is requested in #82

**Comment by luckytaxi** [comment]
I must be missing something, I'm running into the same issue using v5.0.0

# dev/alb-public

```
terraform {
  source = "${get_parent_terragrunt_dir()}/../modules/alb-public"
}

inputs = {
  ...
  ...

  # A list of listener blocks
  # type: list(map(string))
  https_listeners = [
    {
      "port" : "443",
      "protocol" : "HTTPS",
      "target_group_index" = "0"
    }
  ]
}
```

# modules/alb-public/alb.tf
```
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "5.0.0"

  name               = "public-alb-${local.prefix}"
  load_balancer_type = "application"
  security_groups    = var.security_groups
  subnets            = var.subnets
  vpc_id             = var.vpc_id

  https_listeners = var.https_listeners
}
```

**Comment by lobsterdore** [comment]
@vide I encountered a similar issue, you have to specify a default action like so:

```
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "5.10.0"

  http_tcp_listeners = [{
    action_type = "fixed-response"
    default_action = {
      type = "fixed-response"
      fixed_response = {
        content_type = "text/plain"
        message_body = "Not found"
        status_code  = "404"
      }
    }
    port     = 80
    protocol = "HTTP"
    target_group_index = 0
  }]

  internal           = true
  load_balancer_type = "application"
  name               = "my-lb"
  security_groups    = ["security-group-id"]
  subnets            =  ["subnet-id"]
  vpc_id             = ["vpc-id"]
}
```
