### ISSUE TITLE
Support Network Load Balancer Type

### ISSUE THREAD

**Issue by e-moshaya** [terraform-aws-modules/terraform-aws-alb#117]
Can we please variabalise load_balancer_type attribute so that we can select network as the load balancer?

**Comment by antonbabenko** [comment]
[v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) has been just released with NLB support (and more).

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.
