### ISSUE TITLE
Allow adding EIP to Load balancer

### ISSUE THREAD

**Issue by dmattia** [terraform-aws-modules/terraform-aws-alb#125]
**Is your feature request related to a problem? Please describe.**
I want to add a mapping of EIPs to my subnets. This is supported in the `aws_lb` resource as in the following example:

```
resource "aws_lb" "example" {
  name               = "example"
  load_balancer_type = "application"

  subnet_mapping {
    subnet_id     = "${aws_subnet.example1.id}"
    allocation_id = "${aws_eip.example1.id}"
  }

  subnet_mapping {
    subnet_id     = "${aws_subnet.example2.id}"
    allocation_id = "${aws_eip.example2.id}"
  }
}
```

**Comment by antonbabenko** [comment]
[v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) has been just released with NLB support (and more).

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.
