### ISSUE TITLE
Module Always Changing due to health check enabled

### ISSUE THREAD

**Issue by jseiser** [terraform-aws-modules/terraform-aws-alb#126]
**Describe the bug**
This is always showing as a change.

      ~ health_check {
          ~ enabled             = false -> true

**To Reproduce**
```
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "4.1.0"

  load_balancer_name            = "alb-${var.tag_customer}-mfa-${var.tag_environment}"
  security_groups               = ["${module.secgrp_alb.this_security_group_id}"]
  logging_enabled = false
  subnets                       = "${module.vpc.public_subnets}"
  vpc_id                        = "${module.vpc.vpc_id}"
  https_listeners               = "${list(map("certificate_arn", var.alb_iam_cert_arn, "port", 443))}"
  https_listeners_count         = "1"
  target_groups                 = "${list(map("name", "tg-${var.tag_customer}-mfa-${var.tag_environment}-http", "backend_protocol", "HTTP", "backend_port", "80"))}"
  target_groups_count           = "1"

  tags = {
    Terraform   = "true"
    Environment = var.tag_environment
    Customer    = var.tag_customer
    Project     = "mfa"
    Owner       = var.tag_owner
  }
}
```
**Expected behavior**
Health check would default to enabled, and run without showing a change.

**Desktop (please complete the following information):**
Arch Linux
Terraform v0.12.13
+ provider.aws v2.35.0

**Comment by antonbabenko** [comment]
I believe this is not an issue in [v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) which has been just released.

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.

**Comment by jseiser** [comment]
This is still happening on version 5.0.0

```
      ~ health_check {
          ~ enabled             = false -> true
            healthy_threshold   = 2
            interval            = 30
            matcher             = "200-399"
            path                = "/"
            port                = "traffic-port"
            protocol            = "HTTP"
            timeout             = 6
            unhealthy_threshold = 10
        }

```
```
  target_groups = [
    {
      name             = "tg-${var.tag_customer}-mfa-${var.tag_environment}-http"
      backend_protocol = "HTTP"
      backend_port     = 80
      target_type      = "instance"
      health_check = {
        enabled             = true
        interval            = 30
        path                = "/"
        port                = "traffic-port"
        healthy_threshold   = 2
        unhealthy_threshold = 10
        timeout             = 6
        protocol            = "HTTP"
        matcher             = "200-399"
      }
      stickiness = {
        enabled = true
        cookie_duration = 3600
        type = "lb_cookie"
      }
    }
  ]
```

**Comment by antonbabenko** [comment]
Interesting... I don't have an idea of what it can be if you are using fairy recent version of Terraform AWS provider and Terraform (please double-check).

Could you also try to run exactly this example - https://github.com/terraform-aws-modules/terraform-aws-alb/tree/master/examples/complete-alb and tell me if the problem is there also?

**Comment by jseiser** [comment]
We dont specify a AWS provider version, so it should pull the latest on
each run, since this is in a container and not persistent.
Terraform version is 0.12.19

Ill see what i can do to run that example

**Comment by antonbabenko** [comment]
Still, providers can be cached in a few ways, please run `terraform version` to verify.

**Comment by vadixidav** [comment]
I have the same issue, but I am not using `terraform-aws-alb`. Here is my `terraform version`:

```
Terraform v0.12.24
+ provider.aws v2.62.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

Since I am encountering the issue as well without using `terraform-aws-alb`, I think this is an upstream bug.
