### ISSUE TITLE
Default value must have same type as elements in target_group

### ISSUE THREAD

**Issue by tomasbackman** [terraform-aws-modules/terraform-aws-alb#129]
Hi! Great that v5.0.0 is released now with support for tf 0.12. Great work!
However there seem to be some issue with it (I know it is pretty fresh so no surprise)

**Describe the bug**
In my test I'm setting up a simple alb without logging and only http_tcp_listener
```
source = "git@github.com:terraform-aws-modules/terraform-aws-alb?ref=v5.0.0"
load_balancer_type        = "application"
access_logs = {}
https_listeners    = []
http_tcp_listeners = local.http_tcp_listeners
target_groups      = local.target_groups
```
I get:
```
Error: Invalid function argument
  on my_tf_module_using_the_alb, in resource "aws_lb_target_group" "main":
  69:     for_each = length(keys(lookup(var.target_groups[count.index], "health_check", {}))) == 0 ? [] : [lookup(var.target_groups[count.index], "health_check", {})]

Error: Invalid function argument
  on .my_tf_module_using_the_alb, line 85, in resource "aws_lb_target_group" "main":
  85:     for_each = length(keys(lookup(var.target_groups[count.index], "stickiness", {}))) == 0 ? [] : [lookup(var.target_groups[count.index], "stickiness", {})]
```

**Expected behavior**
A alb to be setup

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.1
 - Versions: 
    - Terraform v0.12.9
    - provider.aws v2.35.0

**Comment by tomasbackman** [comment]
Ah it seems like I had "malformed type" for my inputs.. 

From before (4.1.0) I was using test values::
```
http_tcp_listeners = [{ port = "80", protocol = "HTTP", target_group_index = 0 }]
  target_groups = [{
    name                 = "test-http",
    backend_port         = "8511",
    backend_protocol     = "HTTP",
    health_check_matcher = "200",
    health_check_path    = "/ui/"
}]
```
and passed them as:
```
variable "http_listener" {
  type = list(map(string))
}
variable "target_groups" {
  type = list(map(string))
}
```
(and local.xx = var.xx of course)
When changing the variable types to `list(any)` it works

I'm not sure if this varants some code change or clearer documentation, but I'm sharing the find anyway.

**Comment by antonbabenko** [comment]
Thanks, Tomas!

`list(any)` means that this value should be `list` and we don't bother to specify other attributes, because some of them will be string or map. Something like `list(map|string)` would match, but Terraform does not support it and it is fine. :)

Closing this issue, since you found a solution.
