### ISSUE TITLE
Input variable log_location_prefix seem unused?

### ISSUE THREAD

**Issue by tomasbackman** [terraform-aws-modules/terraform-aws-alb#135]
There is an input variable in variables.tf called log_location_prefix. That according to the readme is usedin the s3 logging

However it seems to me like it is not referenced anywhere in main.tf nor output.tf?
Am I missing something? Or is the variable missed?

**Comment by deanvzyl** [comment]
It doesnt seem to be used. I also had a look. If you want to get around the log_prefix issue and have the LB name as the prefix for the logging location just do the following in your access_logs

`access_logs = {
    bucket  = data.terraform_remote_state.itops_prod_state.outputs.itops_s3_logging_bucket.0
    prefix  = "prod-papercut-internal"
    enabled = "true"
  }`

**Comment by tomasbackman** [comment]
Thx , that worked better.

Did a fast PR for removing the unused variable.
https://github.com/terraform-aws-modules/terraform-aws-alb/pull/136
