### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by syquus** [terraform-aws-modules/terraform-aws-alb#153]
Hello,

why there isn't any documentation regarding the usage of the health_checks that are already being supported (and used by this module!) by the [aws_lb resource](https://www.terraform.io/docs/providers/aws/r/lb.html)?

**Comment by antonbabenko** [comment]
Well, there are examples which partially substitute documentation. Have you checked them?

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/06706ac43dadf995ffd6572a9337b1f762e9e7d8/examples/complete-alb/main.tf#L185-L195

**Comment by jaimehrubiks** [comment]
This can also help
https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#health_check
