### ISSUE TITLE
name_prefix example in the README.md character limit

### ISSUE THREAD

**Issue by nahuel242** [terraform-aws-modules/terraform-aws-alb#161]
If someone wants to reuse the example code from the README.md and try to run it, it will fail because the name_prefix argument in the [aws_lb_target_group resource has a 6 character limit](https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#name_prefix) and the current value of "default" has 7 characters 

```
  target_groups = [
    {
      name_prefix      = "default"
      backend_protocol = "HTTPS"
      backend_port     = 443
      target_type      = "instance"
    }
```

I can open a PR to:
- Update the examples in the readme with a name_prefix value of "pref-" o something more useful if someone has a better idea.

- Update in the input section the name_prefix description to address this 6 character limitation

**Comment by antonbabenko** [comment]
Thanks, @nahuel242 for the proposal!

I think it is a good idea to help users to understand all this.

The first item on your list is definitely good, while the second by itself is not enough. Here is what I propose. If you have time, please consider updating Terraform AWS provider documentation for this resource with the same change.

**Comment by nahuel242** [comment]
Hi @antonbabenko , thanks for your suggestions, I'm going to start working on this! 
Regarding the second item, do you refer to [this](https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#name_prefix) documentation? I'm asking because at least that document it's already updated.

Please let me know when you can and I'll start working on this.

Have a nice weekend!

**Comment by antonbabenko** [comment]
Yes, that one. I see it is updated so only the module should be updated.

Best regards,
Anton.

**Comment by nahuel242** [comment]
Closing after merge
