### ISSUE TITLE
Unexpected behavior when changing target group "backend_port"

### ISSUE THREAD

**Issue by temidevops** [terraform-aws-modules/terraform-aws-alb#164]
Hi,

When changing "backend_port" inside the "target_groups" block, the expected behavior is for terraform to delete the current TG and create a new one. 

And indeed on the plan stage, one can see "module.alb.aws_lb_target_group.main[0] must be replaced".
But on the apply stage, I receive the following error:

Error: Error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'mytargetgroupname' exists, but with different settings
	status code: 400, request id: 33a53212-4a74-4f13-a7b5-db5a0bf96ced

Versions:
Terraform v0.12.28
+ provider.aws v2.70.0
alb module is version 5.6.0

I am using Terraform Cloud as remote backend.

**Comment by Dmitry1987** [comment]
probably the reason here is 'create before destroy' and at the time there was no dynamic suffixes (unique IDs) to target groups?
it must be unique name when created. at the moment the described works as expected, with latest version of this module.

**Comment by antonbabenko** [comment]
It is a bit confusing but Dmitry is right. Changing a name is required to prevent errors like `DuplicateTargetGroupName`.
