### ISSUE TITLE
Add support for AWS provider 3.0.0

### ISSUE THREAD

**Issue by ChristophP** [terraform-aws-modules/terraform-aws-alb#165]
the aws provider version 3.0.0 got released a few days ago. This module currently requires version 2 and thus cannot be used with terraform code that used aws provider version 3.

A list of changes: https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0

**Comment by antonbabenko** [comment]
[v5.7.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.7.0) has been just released with the support for AWS provider version 3 and Terraform 0.13.
