### ISSUE TITLE
How create a listener with multiplay rules?

### ISSUE THREAD

**Issue by fatgit** [terraform-aws-modules/terraform-aws-alb#167]
In the [example](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf), I see only one listener - one rule.

But if I need one "forward" and one "redirect"?

**Comment by antonbabenko** [comment]
Hi @fatgit !

I will schedule this issue for live-stream tomorrow - https://www.youtube.com/watch?v=RjblwLq-_bc

There is already a pull-request #155 which I will review then.

**Comment by antonbabenko** [comment]
Please use [v5.9.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.9.0) which has been just released.
