### ISSUE TITLE
Support load_balancing_algorithm_type 

### ISSUE THREAD

**Issue by matteius** [terraform-aws-modules/terraform-aws-alb#169]
The default is round_robin but the ability to specify load_balancing_algorithm_type of "least_outstanding_requests" is desired.  

 I have updated the terraform-aws-alb module we use in our project, but its an older version that the current source I forked from this project.   If I figure out how to make this change in the latest version of terraform-aws-alb I'll submit a pull request for this.

**Comment by matteius** [comment]
Hmmm, it appears maybe the latest version of this module already supports load_balancing_algorithm_type.

**Comment by Dmitry1987** [comment]
doesn't work for me, just tried to use it.. hm..

**Comment by antonbabenko** [comment]
@Dmitry1987 You are right, there is no support for `load_balancing_algorithm_type` in this module yet. PR is welcome.

**Comment by bryantbiggs** [comment]
closed with #158
