### ISSUE TITLE
Invalid value for "default" parameter: the default value must have the same type as the map elements

### ISSUE THREAD

**Issue by jgournet** [terraform-aws-modules/terraform-aws-alb#177]
After upgrading to TF 14.4, I'm getting this error:
```
Error: Invalid function argument

  on .terraform/modules/private_alb/main.tf line 409, in resource "aws_lb_listener" "frontend_https":
 409:         for_each = length(keys(lookup(default_action.value, "authenticate_cognito", {}))) == 0 ? [] : [lookup(default_action.value, "authenticate_cognito", {})]

Invalid value for "default" parameter: the default value must have the same
type as the map elements.
```

After a few tries, I found that this can be bypassed with:
```
      dynamic "redirect" {
        for_each = length(keys(try(lookup(default_action.value, "redirect", {}), {}))) == 0 ? [] : [lookup(default_action.value, "redirect", {})]
```
although ugly, it works.

=> is someone able to either fix it properly, or implement the above at all the places where it fails ?

**Comment by antonbabenko** [comment]
You are right that wrapping expression with `try()` can fix a lot of problems but there has to be a better fix.

1. Which version of Terraform did you use prior to 0.14.4 where things worked well?
2. Can you please run examples in this module and try to reproduce your issue there?

**Comment by jgournet** [comment]
1. Sadly, we went from both:
terraform-aws-modules/terraform-aws-alb 5.0.0 to 5.10.0
and terraform 0.13.4 to 0.14.4
So it might not be related to the TF upgrade (ie: it would probably fail on TF13 as well)

2. Ok ... I just can't reproduce it ! There must be something very specific in our current situation/state that creates this issue.
I'll close this ticket as the module works fine in normal situations.

Thanks for looking at this !

**Comment by garethpelly** [comment]
Encountered this yesterday when upgrading from 5.2 to latest (using TF 0.12.24 recently upgraded aws provider from 2.x to 3.30). Found it could be resolved by changing the following module argument:

```
https_listeners = list(map("certificate_arn", var.cert_arn, "port", 443))
```
to
```
https_listeners = [{certificate_arn = var.cert_arn, port = 443}]
```
