### ISSUE TITLE
ERROR: vpc_id should be set when target type is instance

### ISSUE THREAD

**Issue by vipulparashar** [terraform-aws-modules/terraform-aws-alb#184]
Hi,

Could anyone suggest about the error here - I am not sure the error is correct or maybe I am doing something seriously wrong. I have already provided the vpc_id in the code & still getting this error.

CODE:

resource "aws_lb_target_group" "this" {

  count = length(var.listener_configs)

  name     = "${var.name_prefix}-TG"
  port     = var.listener_configs[count.index].port
  protocol = var.listener_configs[count.index].protocol
  vpc_id   = var.vpc_id

  load_balancing_algorithm_type = var.load_balancing_algorithm_type

  tags = merge(map("Name", "${var.name_prefix}-TG"), var.tags)

}

VARS:

  listener_configs = [{
    port         = 80
    protocol     = "HTTP"
    path_pattern = "/geo/us*"
    priority     = 10
    },
    {
      port         = 80
      protocol     = "HTTP"
      path_pattern = "/geo/eu*"
      priority     = 20
    },
    {
      port         = 80
      protocol     = "HTTP"
      path_pattern = "/geo/ap*"
      priority     = 30
  }]
}

When I am running the code - It's throwing `vpc_id should be set when target type is instance`. I am passing the vpc_id directly from the module.

PROVIDER:
data "aws_vpc" "this" {
  id = var.vpc_id
}

MODULE:
vpc_id  = var.vpc_id

Is this something with terraform or with my code.
Terraform v0.13.3

**Comment by vipulparashar** [comment]
Hi,

Can anyone please suggest something ?

**Comment by bryantbiggs** [comment]
hi @vipulparashar - its quite hard to read what config you have provided, could you wrap your code in [HCL code blocks](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) to render correctly please?
