### ISSUE TITLE
When you remove lambda creation from target group in examples-> complete-alb , the module give errors.

### ISSUE THREAD

**Issue by ranopriyo-neogy** [terraform-aws-modules/terraform-aws-alb#186]
When inside **examples->complete-alb** , I removed below code from target_groups list:

In ideal scenario , there shouldn't be any dependencies between them , but here it does. Curious to know if this can be fixed !

```
{
      name_prefix                        = "l1-"
      target_type                        = "lambda"
      lambda_multi_value_headers_enabled = true
    },

```

**Output**

```
Error: Invalid index

  on ../../main.tf line 398, in resource "aws_lb_listener_rule" "https_listener_rule":
 398:       target_group_arn = aws_lb_target_group.main[lookup(action.value, "target_group_index", count.index)].id
    |----------------
    | action.value is object with 2 attributes
    | aws_lb_target_group.main is tuple with 1 element
    | count.index is 1

The given key does not identify an element in this collection value.

```

**Comment by antonbabenko** [comment]
Target group is referenced by index in `http_tcp_listeners`, `https_listeners` and `https_listener_rules` (search for `target_group_index = 0` in the code).

If you remove it in `target_groups` you need to remove blocks referencing those also.
