### ISSUE TITLE
Target Group Attachment

### ISSUE THREAD

**Issue by bigskygroup** [terraform-aws-modules/terraform-aws-alb#189]
When you add Target Group Attachment support?
or how can I add target instances now?

**Comment by antonbabenko** [comment]
You have to use resources with the output from this module. For eg:

```terraform
resource "aws_lb_target_group_attachment" "workers" {
  target_group_arn = module.alb.target_group_arns[0]
  target_id        = aws_instance.scheduler.id
  port             = 80
}
```

I have no immediate need for this feature myself, so I don't have plans to add it to this module. If anyone has time and understanding - PR is welcome.

**Comment by crash-bandi** [comment]
It appears this merge has made terraform >=13.1 a requirement for ~> 5.0. As documentation states 12.x is supported by ~> 5.0, I would have imagined this would have triggered a major version number update (ie 6.0).  Not sure if this was expected or just missed.

**Comment by antonbabenko** [comment]
@crash-bandi https://github.com/terraform-aws-modules/terraform-aws-alb/issues/195#issuecomment-820316313
