### ISSUE TITLE
The module versions 5.14.0 and newer don't work with Terraform 0.12

### ISSUE THREAD

**Issue by viliakov** [terraform-aws-modules/terraform-aws-alb#195]
## Description

Terraform code, which uses this module with the recommended version pinning `~> v5.0` for Terraform 0.12, can't succeeded with Terraform 0.12 due to pinning to 0.13 version of Terraform (https://github.com/terraform-aws-modules/terraform-aws-alb/blob/v5.14.0/versions.tf#L2)

The error I get:
```
terraform init
Initializing modules...
Downloading terraform-aws-modules/alb/aws 5.15.0 for nlb...
- nlb in .terraform/modules/nlb

Error: Unsupported Terraform Core version

Module nlb (from "terraform-aws-modules/alb/aws") does not support Terraform
version 0.12.29. To proceed, either choose another supported Terraform version
or update the module's version constraint. Version constraints are normally
set for good reason, so updating the constraint may lead to other errors or
unexpected behavior.
```

## Versions

 - Terraform:
Terraform v0.12.29

Your version of Terraform is out of date! The latest version
is 0.15.0. You can update by downloading from https://www.terraform.io/downloads.html
 - Provider(s):
 - Module:

## Reproduction
It can be reproduced with any example from the main page running with Terraform 0.12

### Code Snippet to Reproduce
```module "nlb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "~> 5.0"

  name = "my-nlb"

  load_balancer_type = "network"

  vpc_id  = "vpc-abcde012"
  subnets = ["subnet-abcde012", "subnet-bcde012a"]

  access_logs = {
    bucket = "my-nlb-logs"
  }

  target_groups = [
    {
      name_prefix      = "pref-"
      backend_protocol = "TCP"
      backend_port     = 80
      target_type      = "ip"
    }
  ]

  https_listeners = [
    {
      port               = 443
      protocol           = "TLS"
      certificate_arn    = "arn:aws:iam::123456789012:server-certificate/test_cert-123456789012"
      target_group_index = 0
    }
  ]

  http_tcp_listeners = [
    {
      port               = 80
      protocol           = "TCP"
      target_group_index = 0
    }
  ]

  tags = {
    Environment = "Test"
  }
}
```

## Expected behavior
The module can be used with the recommended pinning  `~> v5.0` and Terraform 0.12

## Actual behavior
The module can't be initialized due to version constraint.

**Comment by antonbabenko** [comment]
Right, please use `version = "5.13.0"` if you are using Terraform 0.12. It should have been a major release, I guess. :-///

This module (as well as all other modules in `terraform-aws-modules` organization) won't support updates for Terraform 0.12. They may continue to work but we will bump the minimum required version once there is a need for that.
