### ISSUE TITLE
Errors if log_prefix, certificate_arn not set

### ISSUE THREAD

**Issue by brandoconnor** [terraform-aws-modules/terraform-aws-alb#2]
From @hasbro-ielo :

The documentation says that log_prefix, certificate_arn are optional.  If I don't set them I get the following:
```
| => tf validate && tf plan
1 error(s) occurred:

* module root: 
    module alb: required variable "certificate_arn" not set
    module alb: required variable "log_prefix" not set
```

Here's how I'm using the module
```
module "alb" {
  source = "modules/terraform-community-modules/tf_aws_alb/alb"

  //alb_is_internal = ""
  //alb_name
  //alb_protocols
  alb_security_groups = "${module.alb_sg.security_group_id_web}"
  aws_region  = "${var.region}"
  aws_account_id = "${var.account_id}"
  //backend_port
  //backend_protocol
  //certificate_arn
  //cookie_duration
  //health_check_path
  log_bucket = "${var.alb_logs_bucket}"
  //log_prefix
  //principal_account_id
  subnets = "${var.alb_subnets}"
  vpc_id = "${module.vpc.vpc_id}"
  //tags
}
```

**Comment by brandoconnor** [comment]
The fix here is two fold:
0. default to HTTP rather than HTTPS, making the barrier to entry lower (no cert required).
1. try to build locals such that if any variables necessary for when certificate_arn, log_prefix, log_bucket, or alb_protocol is HTTPS, if those variables are missing, they are automagically populated with something valid.

**Comment by egarbi** [comment]
@brandoconnor  regarding the second point it would be useful put somewhere in docs that even if you are building an internal alb you need to pass an empty certificate_arn variable

**Comment by brandoconnor** [comment]
@egarbi hmm I think that even brings up a larger point. Why is `certificate_arn` a required variable when some people just want to use HTTP? I'll work through a better approach in the coming release. Thanks for the call out!

**Comment by brandoconnor** [comment]
This should be resolved now.
