### ISSUE TITLE
The module version 5.14.0+ isn't compatible with Terraform 0.12.x as in the documentation

### ISSUE THREAD

**Issue by instcode** [terraform-aws-modules/terraform-aws-alb#200]
## Description

The version 5.14.0+ isn't compatible with Terraform 0.12.x.

## Note

When using the module with version as "~> 5.0" using Terraform 0.12.x, it pulls the latest version which isn't compatible and Terraform raises the following errors:

`Module ecs_alb (from "terraform-aws-modules/alb/aws") does not support
Terraform version 0.12.31. To proceed, either choose another supported
Terraform version or update the module's version constraint. Version
constraints are normally set for good reason, so updating the constraint may
lead to other errors or unexpected behavior`

## Expectation

The documentation should mention this.

## Resolution

I had to specify the version as "5.13.0" to fix the error.

**Comment by antonbabenko** [comment]
Yes, there was a wrong release some time ago. I apologize for that and we moved on to support Terraform 0.13 only across all Terraform AWS modules.
