### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Anik-G** [terraform-aws-modules/terraform-aws-alb#201]
## Description

Please provide a clear and concise description of the issue you are encountering, your current setup, and what steps led up to the issue. If you can provide a reproduction, that will help tremendously.

## ⚠️ Note

$ terraform plan

Error: Invalid expanding argument value

  on alb-nlb.tf line 123, in locals:
 123:   target_group_attachments = merge(flatten([
 124:     for index, group in var.target_groups : [
 125:       for k, targets in group : {
 126:         for target_key, target in targets : join(".", [index, target_key]) => merge({ tg_index = index }, target)
 127:       }
 128:       if k == "targets"
 129:     ]
 130:   ])...)

The expanding argument (indicated by ...) must be of a tuple, list, or set
type.

Error: Unsupported argument

  on alb-nlb.tf line 399, in resource "aws_lb_listener" "frontend_http_tcp":
 399:   tags = merge(

An argument named "tags" is not expected here.

Error: Unsupported argument

  on alb-nlb.tf line 493, in resource "aws_lb_listener" "frontend_https":
 493:   tags = merge(

An argument named "tags" is not expected here.

## Versions

 - Terraform:
 latest
 - Provider(s):
 latest
 - Module:

**Comment by antonbabenko** [comment]
Please make sure to upgrade Terraform AWS provider to version 3.40.0 where `tags` were added (see [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3400-may-13-2021))
