### ISSUE TITLE
Howto use with ASG. Missing example.

### ISSUE THREAD

**Issue by davidkarlsen** [terraform-aws-modules/terraform-aws-alb#204]
## Description

This is more of a question rather than a bug.

How can I use this module with an autoscaling group and still add ALB http health checks?
https://github.com/terraform-aws-modules/terraform-aws-autoscaling#input_target_group_arns takes the tg as an arn, but at the same time I need to define health_check within the target_group in this module.
And what should the target_type be then? 

Maybe this could be added to the examples?

**Comment by antonbabenko** [comment]
Hi David!

`target_type` can be `instance` or `lambda` (eg, https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf#L275 )

Autoscaling group accepts `target_group_arns` and it is not related to a health check defined inside of `target_groups` by this module.

**Comment by antonbabenko** [comment]
There is also a decent example in autoscaling module - https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/complete/main.tf#L414

**Comment by davidkarlsen** [comment]
Thanks for the quick answer, that example uses EC2 health checks https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/examples/complete/main.tf#L523, while I want to add health checks in the ALB. When running with instances I could do this:

```
target_groups = [
    {
      backend_protocol = "TCP"
      backend_port     = local.meta_defender_port
      target_type      = "instance"
      targets = {
        for instance in aws_instance.md_instance :
        instance.id => {
          target_id = instance.id
          port      = local.meta_defender_port
        }
      }
      health_check = {
        enabled             = true
        interval            = 30
        path                = "/stat/engines"
        port                = "traffic-port"
        healthy_threshold   = 3
        unhealthy_threshold = 3
        timeout             = 6
      }
```

but not sure how to make that work with ASG and this module.

**Comment by prachikhadke** [comment]
I think the issue is that this module allows us to add instances as targets to the target group. but not an autoscaling group. what happens when an instance in an autoscaling group dies and a new one spins up. Is there a way to add it to the target group automatically?

**Comment by antonbabenko** [comment]
@prachikhadke See my comment above - https://github.com/terraform-aws-modules/terraform-aws-alb/issues/204#issuecomment-850267376

**Comment by HyperMe1200** [comment]
It would be great to have an example how to use this module with very common pattern of ALB and ASG usage in AWS - one shared ALB with hostname/path based routing + multiple ASGs and TGs.

**Comment by vishwa-trulioo** [comment]
@antonbabenko I think this requirement can be improved by adding support using `aws_autoscaling_attachment` terraform resource in this module. Because as per the way the flow works in this module, this module is nicely built to manage necessary attachments at the load balancer level. Hence, adding ASG attachment capability in this module makes sense than at the ASG level I think.

**Comment by antonbabenko** [comment]
`aws_autoscaling_attachment` - is related to an Autoscaling group, to my mind. It can be added into [terraform-aws-autoscaling module](https://github.com/terraform-aws-modules/terraform-aws-autoscaling/), if necessary.
