### ISSUE TITLE
Unable to upgrade to version 5 without ALB recreation 

### ISSUE THREAD

**Issue by gtonello** [terraform-aws-modules/terraform-aws-alb#205]
## Description

I'm facing a situation that I already have an ALB deployed in AWS with an old version of this module, and now I'm trying to upgrade it to v5.0 without an ALB recration. But doesn't matter what I do, I'm always seen an ALB recreation on my execution plan.
I also have an issue when applying this change because of `create_before_destroy` flag since that my ALB already exists on `tfstate` file raising  a `DuplicateName` error. 

Is there a way to avoid these issues on my upgrade? I really like to avoid an ALB recreation here.

P.S.: It's only a question related to the module, not a bug.

## Versions

 - Terraform: 0.12.31

 - Provider(s): AWS 3.42.0

 - Module: 5.13

**Comment by antonbabenko** [comment]
Hi!

There is an upgrade guide explaining what has changed in 5.0 - https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md

You should run `terraform state` commands to perform such an upgrade. Please consult the official documentation for Terraform on this subject.
