### ISSUE TITLE
Misleading Error Message -  The argument "condition" is required, but no definition was found.

### ISSUE THREAD

**Issue by Ashtonian** [terraform-aws-modules/terraform-aws-alb#209]
## Description

When setting up https listener rules if condition property does not match one of the expected condition types ie mistyping `host_headers` as `host_header` it will error with The argument "condition" is required, but no definition was found which is wrong as the condition block is provided its just wrong.  

## Versions

 - Terraform: .14.10

 - Provider(s): aws 3.43

 - Module: 6.2

## Reproduction

Attempt to use module with listener snippet below. 

### Code Snippet to Reproduce

```
  https_listener_rules = [
    {
      https_listener_index = 0
      priority             = 1
      actions = [
        {
          type               = "forward"
          target_group_index = 0
        }
      ]
      conditions = [
        {
          host_header = ["someheader"]
        }
      ]
    },
  ]
```

## Expected behavior

Better validation with an actionable error message. 

## Actual behavior
```
  on .terraform/modules/alb/main.tf line 142, in resource "aws_lb_listener_rule" "https_listener_rule":
 142: resource "aws_lb_listener_rule" "https_listener_rule" {
The argument "condition" is required, but no definition was found.
```

**Comment by antonbabenko** [comment]
Hi @Ashtonian !

All error messages are coming from Terraform and we can't control them in the module.

I recommend looking into the examples to understand how certain features should be configured.

**Comment by DeLoWaN** [comment]
Lost 45 min on this too. I actually had the same issue with `host_header` instead of `host_headers`. Fortunately, this ticket point me to the problem.

**Comment by antonbabenko** [comment]
Closing this issue because there is nothing we can/will be able to do in the module.
