### ISSUE TITLE
Feature request: Support weight in forward action

### ISSUE THREAD

**Issue by siutsin** [terraform-aws-modules/terraform-aws-alb#211]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

I am looking for a weighted forward action described at [lb_listener_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule#weight). However, it seems [it is not currently supported](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/e643496d985dc07a406cac025bc63c4bb10371e7/main.tf#L237-L249) in this module.

## Describe the solution you'd like.

Support the syntax described in lb_listener_rule. E.g.

```
resource "aws_lb_listener_rule" "host_based_routing" {
  listener_arn = aws_lb_listener.front_end.arn
  priority     = 99

  action {
    type = "forward"
    forward {
      target_group {
        arn    = aws_lb_target_group.main.arn
        weight = 80
      }

      target_group {
        arn    = aws_lb_target_group.canary.arn
        weight = 20
      }

      stickiness {
        enabled  = true
        duration = 600
      }
    }
  }

  condition {
    host_header {
      values = ["my-service.*.terraform.io"]
    }
  }
}
```

**Comment by alexbricepalo** [comment]
+1 for this feature

**Comment by alexbricepalo** [comment]
https://github.com/terraform-aws-modules/terraform-aws-alb/pull/224
