### ISSUE TITLE
Make security groups parameter optional when creating ALB

### ISSUE THREAD

**Issue by canidam** [terraform-aws-modules/terraform-aws-alb#212]
## Is your request related to a problem? Please describe.

I manage my security groups outside of terraform. The module requires to get security group as a parameter, which clears any attached security group to the alb resource.

## Describe the solution you'd like.

Make this parameter optional. If it isn't provided, ignore the configuration of the security groups. The change is minor, and improves the flexibility of the module.

**Comment by vishwa-trulioo** [comment]
To create an ALB or any LB you **_must_** provide at least one security group id as per AWS. Thats why this is needed. You can manage the rules and other config of the security group outside of this module. I don't think it is possible to make this optional.
