### ISSUE TITLE
Is it possible to create http listener rules?

### ISSUE THREAD

**Issue by Erokos** [terraform-aws-modules/terraform-aws-alb#214]
Hi this isn't a bug report but rahter a question on how to specify http rules? I can see in the examples rules for https listeners but not for http. Can this be achieved by using this module? Thank you kindly in advance fir your answers.

**Comment by florian0410** [comment]
Sounds like a dupplicate from https://github.com/terraform-aws-modules/terraform-aws-alb/issues/176.

I think a PR based on `https_listener_rules` version could help to make it happen.

Regards
