### ISSUE TITLE
Add Ignore Changes Lifecycle to Listener Rules

### ISSUE THREAD

**Issue by fdmsantos** [terraform-aws-modules/terraform-aws-alb#219]
Is possible add dynamic input to ignore changes in Forward Target Group in Listener Rules Actions?

### Use Case

My Target groups in Listener rules actions are controlled by ECS Blue Green Deployment. If this module don't ignore these changes, will break up my application

### Possible Code

I had to create the listener outside this module. This work adding this code to aws_lb_listener_rule resource:
`
lifecycle {
    ignore_changes = [action[0].target_group_arn]
  }
`

Thanks for all your great work on Terraform AWS Modules.

Regards,
Fábio Santos

**Comment by antonbabenko** [comment]
Hi Fábio!

Unfortunately, it is not possible to use variables in `lifecycle` in Terraform, so we can't do it in the module.

**Comment by jfair9** [comment]
We are facing the same issue. Was there an alternative solution?

**Comment by ndench** [comment]
Unfortunately, the only workaround I've found is to manually define the target groups and listener outside of the module.

So I removed my `https_listeners` and `target_groups` from the module:

```hcl
module "alb" {
  // ...
  
  https_listeners = [
    {
      target_group_index = 0
      // ...
    },
  ]

  target_groups = [
    {
      name = "blue"
      // ...
    },
    {
      name = "green"
      // ...
    }
  ]
  
  // ...
}
```

And replaced them with manual resources:

```hcl
resource "aws_lb_target_group" "ecs_blue" {
  name = "blue"

  // ...

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_lb_target_group" "ecs_green" {
  name        = "green"

  // ...

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_lb_listener" "https" {
  load_balancer_arn = module.alb.lb_arn

  // ...

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.ecs_blue.arn
  }

  lifecycle {
    ignore_changes = [default_action]
  }
}
```

That then allows me to `ignore_changes = [default_action]`

It would be great if this module could somehow support this. Although, I have no idea how that would work, given the limitations on modules.
