### ISSUE TITLE
Associate WAF to Loadbalancer

### ISSUE THREAD

**Issue by fdmsantos** [terraform-aws-modules/terraform-aws-alb#220]
Hi,

Is possible this module associate a waf to the Load Balancer?

`resource "aws_wafregional_web_acl_association" "foo" {
  resource_arn = aws_alb.foo.arn
  web_acl_id   = aws_wafregional_web_acl.foo.id
}`

Thanks for the great work.

Regards

**Comment by antonbabenko** [comment]
Yes, it is possible to have if you can send a PR.
