### ISSUE TITLE
Preserve item identities in collections

### ISSUE THREAD

**Issue by kevinresol** [terraform-aws-modules/terraform-aws-alb#234]
## Is your request related to a new offering from AWS?

No

## Is your request related to a problem? Please describe.

Let's take `https_listeners` as an example, suppose we have:

```hcl
https_listeners = [
  {port = 8001, target_group_index = 0},
  {port = 8002, target_group_index = 1},
]
```

then later we want to remove the first listener:

```hcl
https_listeners = [
  {port = 8002, target_group_index = 1},
]
```

When applied, terraform will plan to modify the 1st listener (from port:8001 to port:8002) and delete the 2nd listener(port:8002).
This is not ideal because sometimes this will cause a race condition where the 1st listener is modified before the deletion of the 2nd one is completed, thus resulting in a "port already in use" error.

## Describe the solution you'd like.

Since currently the information is stored as a list and the resources are declared with a `count` metadata, the identity of each item is not preserved thus causing the said behaviour. A better approach would be to use `for_each` with a map such that each item can preserve their identity via the map key.

Example:

```hcl
https_listeners = {
  foo = {port = 8001, target_group_index = 0},
  bar = {port = 8002, target_group_index = 1},
]
```

in such case when we want to remove the "foo" listener, "bar" will be untouched at all.

**Comment by antonbabenko** [comment]
Thanks for opening this issue!

I agree with what you are saying here. We should use `for_each` and migrate away from using `count`. Similar to how we have done in many other modules ([EKS](https://github.com/terraform-aws-modules/terraform-aws-eks), [RDS](https://github.com/terraform-aws-modules/terraform-aws-rds), [RDS Aurora](https://github.com/terraform-aws-modules/terraform-aws-rds-aurora)). If anyone wants to make a PR, I won't stop them.
