### ISSUE TITLE
output "alb_listener_http_id  is not laways useful

### ISSUE THREAD

**Issue by proj4spes** [terraform-aws-modules/terraform-aws-alb#24]
to add a listener rule  to the listener is required the resource's ARN  and there is no way to convert id to arn. it would nice to have boyh arn and id (also for https listener)

**Comment by brandoconnor** [comment]
Hey, @proj4spes. Good point and that's a fine suggestion for a new couple of outputs. If you wanted to take a stab at the PR, I'd be happy to review and get that shipped. I'll batch it in my next set of changes (by end of week) if not.

**Comment by proj4spes** [comment]
hi @brandoconnor ,  before to make the pull request , I'd prefer discuss the modification with you .
now the alb_listener_http_id  output is given in a list , but as long as the module outputs each single protocol  (http and https) listener  , the list will be always of one elements. In addition if you gets back more than one listener arn (??) you have no way to understand to which  attach your listener rule(s)

so the modif would be :

`output "alb_listener_https_id" {
  description = "The ID of the ALB Listener we created."
  value       = "${element(concat(aws_alb_listener.frontend_https.*.id, list("")), 0)}"
}
output "alb_listener_https_arn" {
  description = "The ID of the ALB Listener we created."
  value       = "${aws_alb_listener.frontend_https.arn }"
}

output "alb_listener_http_id" {
  description = "The ID of the ALB Listener we created."
  value       = "${element(concat(aws_alb_listener.frontend_http.*.id, list("")), 0)}"
}
output "alb_listener_http_arn" {
  description = "The ID of the ALB Listener we created."
  value       = "${aws_alb_listener.frontend_http.arn}"
}
`

**Comment by brandoconnor** [comment]
The reason the listener ids outputs are formatted as a list (but not actually a list, only ever a single element) is due to [this upgrade workaround](https://www.terraform.io/upgrade-guides/0-11.html#referencing-attributes-from-resources-with-count-0). Likewise, we cannot be certain that a user would create an HTTP listener, an HTTPS listener or both so the module has to account for the absence of resources it outputs. Using this pattern, the following lines need to be added for your proposed change:

```
output "alb_listener_http_arn" {
description = "The ARN of the HTTP ALB Listener we created."
value       = "${element(concat(aws_alb_listener.frontend_http.*.arn, list("")), 0)}"
}

output "alb_listener_https_arn" {
description = "The ARN of the HTTPS ALB Listener we created."
value       = "${element(concat(aws_alb_listener.frontend_https.*.arn, list("")), 0)}"
}
```

That should work.

**Comment by proj4spes** [comment]
hi , I get it  and now should I do the pull request or you are going everything by yourself ?
sorry for my english

**Comment by brandoconnor** [comment]
The English is no problem. I appreciate the suggestion and help.

Since you came up with the idea, I'll give you the opportunity to make the change and submit the PR. Reply here again if you need help. 👍

**Comment by brandoconnor** [comment]
This has been merged, closing the issue.
