### ISSUE TITLE
Cannot set cookie_name for stickiness

### ISSUE THREAD

**Issue by SaschaKoth** [terraform-aws-modules/terraform-aws-alb#242]
## Description

I'm setting the cookie_name attribute for stickiness (type app_cookie) in the target group of my ALB, but terraform throws the following error:

Error: error modifying Target Group Attributes: InvalidConfigurationRequest: You must set an application cookie name to enable stickiness of type 'app_cookie'
status code: 400, request id: cfc9f449-6bb9-4186-90aa-780d6cc825db

## Versions
 - Terraform: 1.1.7
 - Provider(s):
provider registry.terraform.io/hashicorp/aws v4.4.0
provider registry.terraform.io/hashicorp/random v3.1.0
 - Module:6.7.0
 
## Reproduction
- Added stickiness block to target_group of  alb
- run terraform apply

### Code Snippet to Reproduce
      stickiness = {
        enabled = true
        cookie_name = "AUTH_SESSION_ID"
        type = "app_cookie"
      }

## Expected behavior
Add stickiness with application cookie name to alb 

## Actual behavior
Doesn't add cookie_name to terraform state file (cookie_name in state file is "") and throws error

**Comment by antonbabenko** [comment]
This issue has been resolved in version 6.10.0 :tada:
