### ISSUE TITLE
Politicised Terraform Resources?

### ISSUE THREAD

**Issue by adelwin** [terraform-aws-modules/terraform-aws-alb#246]
## Description

First, let me start by saying that I am not supporting or against Russia or Ukraine. I just think that it's way above my head. I try my best not to make any judgement on these things.

Second, I think that on one side we have engineers/developers/technical-people all across the globe and they can be from anywhere, but on the other side, there's no denying that some very talented engineers can either come from Ukraine or Russia.

With that, I dont think a "code-repository" is the place to pledge support to certain side of a war.

Does this mean that this repo will no longer accept any PR from Russian engineers? Does this mean that terraform-aws should not be used or be able to be pulled from Russia?

I simply think that this isn't the place for political affiliations. Code should be like music. Good music is just good music, regardless of where it came from.

So, can we please stop with this?
This is all over the place, the banner, and now the extra optional input?
<img width="804" alt="image" src="https://user-images.githubusercontent.com/6689484/165941686-c9addccc-f066-4e8c-a72b-6445a61e6ee1.png">

**Comment by antonbabenko** [comment]
Answering your questions.

> Does this mean that this repo will no longer accept any PR from Russian engineers?
I don't care where people are coming from as long as they agree with the statements you found out.

> Does this mean that terraform-aws should not be used or be able to be pulled from Russia?
Preferably, yes.

> So, can we please stop with this?
No. We stop when Ukraine wins.

>This is all over the place, the banner, and now the extra optional input?
Yes, this is how it is.

I am going to close this issue.

**Comment by adelwin** [comment]
I've mentioned that I'm neither pro nor against any sides.

My point is just that "a code repository isn't the place to pledge your political affiliations to any sides of war". 

Plus, all other aws modules have the flag but none have the additional variables. 

I've accepted the fact that we disagree.
