### ISSUE TITLE
stickiness feature

### ISSUE THREAD

**Issue by ssnigoro** [terraform-aws-modules/terraform-aws-alb#247]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider

Please help to get how can I use something like block for sticky session with alb module.
Like:
```
 stickiness {
    enabled = true
    type    = "lb_cookie"
 }
``` 
no any examples or help was added for that case

## Describe the solution you'd like.
probably solution is already existing but will be good to know

## Describe alternatives you've considered.
tried to use separate resource but no luck as well
```
resource "aws_lb_cookie_stickiness_policy" "this" {
  name                     = "stickiness"
  load_balancer            = module.alb.lb_id
  lb_port                  = 443
  cookie_expiration_period = 600
}
```
getting 
`ValidationError: LoadBalancer name cannot be longer than 32 characters`

**Comment by antonbabenko** [comment]
Hi,

In ALB/NLB there is this setting:

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/596cc0f30f84f0b5f28570aab10f9eee10eed8d5/examples/complete-alb/main.tf#L268-L271

The resource you described - `aws_lb_cookie_stickiness_policy` - is for ELB Classic. We have a dedicated module for it - https://github.com/terraform-aws-modules/terraform-aws-elb - and the resource you mentioned is not available there. If you wish to contribute, please open a PR there.
