### ISSUE TITLE
For ALB rules, can use the target group name instead of target_group_index? 

### ISSUE THREAD

**Issue by dnyaneshwarsonawane** [terraform-aws-modules/terraform-aws-alb#248]
For ALB rules, can use the target group name instead of target_group_index? 

I think It will easy to manage and readable especially when you have multiple rules and target groups.

**Comment by antonbabenko** [comment]
It will require some backward-incompatible changes to the module. We will do it at some point but not sure when exactly.

**Comment by naomichi-y** [comment]
I also have the same problem.
It would be very helpful if I could specify the target on a name basis.
