### ISSUE TITLE
Add support for terminating connection in the Target Group resource

### ISSUE THREAD

**Issue by kitos9112** [terraform-aws-modules/terraform-aws-alb#256]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

The Terraform resource `aws_lb_target_group` allows to configure the connection_termination behaviour in the target group. This is available in the provider.

## Describe the solution you'd like.

A new entry to the existing `target_groups` KVP input variable that contemplates adding support for this request.

## Describe alternatives you've considered.

NA

## Additional context

I'll be raising an MR to add this behaviour.

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.1.0 :tada:
