### ISSUE TITLE
Terraform code to add multiple ssl certificates to ssl listener

### ISSUE THREAD

**Issue by satish-chef** [terraform-aws-modules/terraform-aws-alb#26]
Hello,

Can you please add terraform code to add multiple certificates to SSL listener since ALB now supports binding of up to 25 certificates on its listener as per https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/

**Comment by brandoconnor** [comment]
Good suggestion, @satish-chef . I'll look to add this in the next round release. If you have a good idea of how to implement, feel free to submit a PR for review.

**Comment by shakefu** [comment]
Just hit this use case myself - would love to see something like this:

```hcl
resource "aws_elb" "my_elb" {
  # <SNIP>
  listener {
    instance_port      = 8080
    instance_protocol  = "tcp"
    lb_port            = 443
    lb_protocol        = "ssl"
    ssl_certificates = [
      "${aws_iam_server_certificate.domain.arn}",
      "${aws_iam_server_certificate.other_domain.arn}"
    ]
  }
}
```

**Comment by brandoconnor** [comment]
Yea I think the `certificate_arn` variable needs to be changed to be a list throughout. If either of you want to take on that PR, definitely do. Otherwise, when I have a moment to spare on the project, it'll be prioritized. Thanks for adding the use case!

**Comment by luisamador** [comment]
Just hit this issue myself too, would be pretty useful to be able to add multiple ssl certs to the ALB, at the moment we are doing this via the AWS console but our changes get overwritten after we deploy changes via Terraform :(

**Comment by brandoconnor** [comment]
^ Gotcha @luisamador . Help is on the way. I've got a release queued up locally that will solve the issue within a day or so. Just need to get tests working at this point.

**Comment by brandoconnor** [comment]
@satish-chef , @shakefu , @luisamador -

Sorry everyone. It turns out this isn't possible at the moment with the current aws terraform provider. We're blocked upstream until the feature is implemented. From what I can tell, that attribute [is of type string](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lb_listener.go#L64) everywhere in the upstream source. If this is high pri enough for you, definitely [file an issue to that repo](https://github.com/terraform-providers/terraform-provider-aws/issues).

I'm going to close this in the meantime as there's nothing actionable here until upstream accommodates.

**Comment by brandoconnor** [comment]
Reopening as I checked up on your issue here https://github.com/terraform-providers/terraform-provider-aws/issues/3843 and can see how it'd be implemented now. I'll have that released in no time.

**Comment by luisamador** [comment]
Thank you very much @brandoconnor .

**Comment by brandoconnor** [comment]
Released under 3.1.0

**Comment by satish-chef** [comment]
@brandoconnor Thanks you very much ! 👍

**Comment by dking3876** [comment]
Can someone point me to the documentation for this?  all current docs still reflect using on one single arn

**Comment by ladean** [comment]
I came across this link in case someone else stumbles upon this thread.

https://www.terraform.io/docs/providers/aws/r/lb_listener_certificate.html

**Comment by nikolaigauss** [comment]
I've a question about this old issue, should we want to add more certificates to an HTTPS listener... Can we use a list in the certificates_arn (currently not working for me)? Or should we use this resource:
`resource "aws_lb_listener_certificate" "example" {
  listener_arn    = aws_lb_listener.front_end.arn
  certificate_arn = aws_acm_certificate.example.arn
}`
using the module's output.

**Comment by OlivierCuyp** [comment]
@nikolaigauss, here is what worked for me:

```tf
resource "aws_lb_listener" "com-mysite-alb-listener" {
  load_balancer_arn = aws_lb.com-mysite-alb.arn
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2016-08"
  # Default certificate
  certificate_arn   = aws_acm_certificate_validation.com-mysite-mysite-com.certificate_arn

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.com-mysite-target-group-manager.arn
  }
}

# Additional certificate for the .net
resource "aws_lb_listener_certificate" "com-mysite-alb-listener-certificate" {
  listener_arn    = aws_lb_listener.com-mysite-alb-listener.arn
  certificate_arn = aws_acm_certificate_validation.com-mysite-mysite-net.certificate_arn
}

# Additional certificate for the .org
resource "aws_lb_listener_certificate" "com-mysite-alb-listener-certificate" {
  listener_arn    = aws_lb_listener.com-mysite-alb-listener.arn
  certificate_arn = aws_acm_certificate_validation.com-mysite-mysite-org.certificate_arn
}
```

Hope this helps...

**Comment by nikolaigauss** [comment]
@OlivierCuyp yeah, that's something similar than what I've done, I was hoping for the module to do the attachments rather than calling a separate resource per additional certificate you want to add to the listener, if that makes sense...

It's not the end of the world tho, I'm happy using it this way :)
