### ISSUE TITLE
target_group re-ordering, duplicate names, can agree to use maps?

### ISSUE THREAD

**Issue by ericb-summit** [terraform-aws-modules/terraform-aws-alb#278]
First of all thanks for the effort you guys put into these modules it is very much appreciated.

Bringing back #254 which in short, makes it impossible to use this module if the data feeding `target_groups` and `https_listeners` is a map.

Why is it impossible?

1) If you feed data from a map, and add to that map, a new say, `target_group` could be added in position 1 of N, pushing the rest of them down, forcing them to re-create.

2) `create_before_destroy = true` makes a simple re-ordering of target groups barf with "target group already exists", making seemingly simple tasks impossible. Yes I know the "workaround" i.e change the TG name but my name is computed from inputs related to that target group, not ids happenstance ordinal position.

In years of working with tf, I have realized using `count` with a count that isn't 0/1 is asking for trouble as it makes it unimaginably painful to create dynamic resources.   I am also extremely careful with `create_before_destroy` that AWS actually allows you to do it, consistently, always, and doesn't fail in obscure, unintuitive ways.

I plan to fork and add `target_group_map` and `https_listeners_map` params to supplement the legacy stuff.  If you are at all interested in a PR, I can make it variable/outputs backwards compatible.

Thanks again.

EDIT - I see now how much your use of lists is just intrinsic to the interface design

**Comment by jameshopkins** [comment]
I'd be interested in this work, too.

Fundamentally if list order isn't absolutely required, there are major disadvantages to using a list.

**Comment by ericb-summit** [comment]
@jameshopkins  https://github.com/summittech-ca/terraform-aws-alb/commit/983474f349af31584977c9ebb57f62fd39744fa4

**Comment by LeandroMichelson** [comment]
Any progress on this matter?

The behavior reported by @ericb-summit is perfect for me.

**Comment by ericb-summit** [comment]
@LeandroMichelson see https://github.com/terraform-aws-modules/terraform-aws-alb/compare/master...summittech-ca:terraform-aws-alb:master

Not to break backwards compat I added *_map variants of some variables and then I merge the ordinal list and the map items together before doing a `for_each` in lieu of a `count`.

Do I even bother submitting a PR?
