### ISSUE TITLE
`enable_xff_client_port` default to true is a breaking change for apps that rely on `x-forwarded-for` as its now including port by default

### ISSUE THREAD

**Issue by Prasad1826** [terraform-aws-modules/terraform-aws-alb#286]
`enable_xff_client_port` default to true is a breaking change for apps that rely on `x-forwarded-for` as its not including port by default

_Originally posted by @Prasad1826 in https://github.com/terraform-aws-modules/terraform-aws-alb/issues/284#issuecomment-1487931796_

**Comment by antonbabenko** [comment]
[enable_xff_client_port](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#enable_xff_client_port) is `true` in AWS provider. You can change it to `false` if you need.

**Comment by caseyclarkjamf** [comment]
I ran into this today as well and think it should default to `false` to align with the Terraform provider behavior and also the default behavior when creating an ALB through the AWS console: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#enable_xff_client_port

**Comment by AdamJCavanaugh** [comment]
@antonbabenko , please consider re-opening this issue as the AWS provider does (now) default to false, which is the opposite behavior of this module.
