### ISSUE TITLE
Not in Terraform Module Registry

### ISSUE THREAD

**Issue by alexjurkiewicz** [terraform-aws-modules/terraform-aws-alb#29]
Hi, is there a reason this module isn't in the terraform module registry? Is there an issue that needs to be fixed?

**Comment by brandoconnor** [comment]
I can see it and it's linked in the README. Does this link work for you?: https://registry.terraform.io/modules/terraform-aws-modules/alb/aws

**Comment by alexjurkiewicz** [comment]
Ah, unlike other "terraform-aws-modules" packages, it's not verified, so it doesn't show up by default when you search:
https://registry.terraform.io/search?q=alb
I guess I'm curious why it's not verified, but I can see it now :)

**Comment by brandoconnor** [comment]
Thanks for looking out. I emailed the hashicorp team about it and they never got back to me. Unsure of how to get it to verified :shrug:
