### ISSUE TITLE
Add WAF web_acl association

### ISSUE THREAD

**Issue by rickychew77** [terraform-aws-modules/terraform-aws-alb#292]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.
To add WAF web acl association

## Describe the solution you'd like.
In PR #291

**Comment by c0debreaker** [comment]
I also need WAF ACL association. Is it being worked on?

**Comment by ryanoolala** [comment]
Am looking for this as well, was there a reason it is not included in this module?

**Comment by antonbabenko** [comment]
This issue has been resolved in version 8.7.0 :tada:

**Comment by antonbabenko** [comment]
The main reason for not having things at the same moment as PR opens is lack of time.

**Comment by ryanoolala** [comment]
thx!
