### ISSUE TITLE
At least 1 "condition" blocks are required.

### ISSUE THREAD

**Issue by myroslavmail** [terraform-aws-modules/terraform-aws-alb#293]
I've got the following Lb, with two target groups and **it was working fine until I've started to add "https_listener_rules" block.** But I need that block and not sure where the issue is. The idea is -I've got 2 target groups and want to create rule which would forward my request to specific target group, based on the host_header which I've declared. 

For some reason adding this block gives me `"At least 1 "condition" blocks are required."` error.

What can be wrong or is it an issue?

```
module "proxy-lb-public" {
  source                    = "terraform-aws-modules/alb/aws"
  version                   = "8.6.0"

  name                      = "proxy-lb-public"
  subnets                   = ["subnet-054a44658bdef", "subnet-09660d6a8c5a8", "subnet-0de76b0bacc82","subnet-053bc7344fd88"]
  security_groups           = ["sg-0770e7c905"]
  vpc_id                    = "vpc-03becc4c7"
  load_balancer_type        = "application"
  enable_xff_client_port    = "false"
  target_groups             = [
    {
      name                  = "proxy"
      deregistration_delay  = "180"
      backend_protocol      = "HTTP"
      backend_port          = "80"
      target_type           = "instance"
      targets = [
        {
          target_id         = "i-0d63d2bbe0a2"
          port              = 80
        }
      ]
      health_check          = {
          matcher           = "200,301,401"
      }
      tags                  = var.common_tags
    },
    {
      name                  = "dev-vpn"
      deregistration_delay  = "180"
      backend_protocol      = "HTTPS"
      backend_port          = "443"
      target_type           = "instance"
      targets = [
        {
          target_id         = "i-054c767346ad"
          port              = 443
        }
      ]
      health_check          = {
          matcher           = "200-399"
      }
      tags                  = var.common_tags
    }
  ]

  https_listeners           = [
    {
      port                  = 443
      protocol              = "HTTPS"
      certificate_arn       = aws_acm_certificate.domain1.arn
      target_group_index    = 0
      ssl_policy            = "ELBSecurityPolicy-TLS-1-2-2017-01"
    }
  ]

  https_listener_rules 	    = [
    {
    https_listener_index    = 0


    actions 		    = [
      {
      type        	    = "forward"
      target_group_index    = 0
      }
    ]

    conditions              = [
      {
      host_header 	    = ["vpn.domain1.com"]
      }
    ]

    }
  ]

  extra_ssl_certs           = [
    {
      certificate_arn       = aws_acm_certificate.domain1.arn
      https_listener_index  = 0
    },
    {
      certificate_arn       = aws_acm_certificate.domain2.arn
      https_listener_index  = 0
    }
  ]


  http_tcp_listeners        = [
    {
      port                  = 80
      protocol              = "HTTP"
      action_type           = "redirect"
      redirect = {
        port                = "443"
        protocol            = "HTTPS"
        status_code         = "HTTP_301"
      }
    }
  ]

  tags                      = var.common_tags
}
```

**ps. resources named here are dummy-named**

**Comment by maksim-travnikov** [comment]
Hello, @myroslavmail, it's typo in your conditions, host_header => host_header**s**

**Comment by myroslavmail** [comment]
@maksim-travnikov on one hand - I'm appreciated for the answer, indeed it does the job, thank you. The misleading thing is, the official documentation for [lb_listener_rule here ](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule) refers to the directive as "host_header" so I assumed it is AXIOM, especially when on dedicated module page that [you've created here](https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest) there is ZERO mentioning about how should it be written.    ... and that's kind of a trouble and thus caused and may cause issues

**Comment by myroslavmail** [comment]
and in addition the error is kind of misleading too. I think I've got the "condition" block, but actually the mistake was within the condition block itself, if possible needs to be more precise

**Comment by bryantbiggs** [comment]
It is shown in the example - https://github.com/terraform-aws-modules/terraform-aws-alb/blob/286b327c8a71d74f490080c9d0a6dbfcdb2db0b8/examples/complete-alb/main.tf#L227

Closing with the guidance provided above
