### ISSUE TITLE
Weighted target groups don't work

### ISSUE THREAD

**Issue by romogo17** [terraform-aws-modules/terraform-aws-alb#299]
## Description

The current way of defining `target_group_arn` doesn't allow the use of multiple weighted target groups. 

As per the [`lb_listener#target_group_arn`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener#target_group_arn) documentation:

> `target_group_arn` - (**Optional**) ARN of the Target Group to which to route traffic. Specify only if `type` is `forward` and you want to route to a **single target group**. To route to one or more target groups, use a `forward` block instead.

> `forward` - (...) If you specify both `forward` block and `target_group_arn` attribute, you can specify only one target group using `forward` and it must be the same target group specified in `target_group_arn`.

The way the `target_group_arn` is currently defined means that this value will always have a value if the `action_type` is `forward` (default). This means that when using multiple target groups in the forward block, the single `target_group_arn` will take precedence. 

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/cb8e43d456a863e954f6b97a4a821f41d4280ab8/main.tf#L638

This was previously [mentioned](https://github.com/terraform-aws-modules/terraform-aws-alb/issues/280#issuecomment-1556389320) in this comment in a related issue

## Possible fix

Make the `target_group_arn` condition also check if there's more than one target group. I tested this in the terraform console with this expression

```hcl
length(lookup(lookup(default_action.value, "forward", {}), "target_groups", []))
```
With the full expression being something like this:

```hcl
target_group_arn = contains([null, "", "forward"], lookup(default_action.value, "action_type", "")) && length(lookup(lookup(default_action.value, "forward", {}), "target_groups", [])) < 2 ? aws_lb_target_group.main[lookup(default_action.value, "target_group_index", count.index)].id : null
```

## Versions

- Module version [Required]: `v8.7.0`
- Terraform version:
```
terraform -version
Terraform v1.3.4
on darwin_arm64
```
- Provider version(s):
```
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.10.0
```

## Reproduction Code [Required]

I believe the example code should be enough to reproduce this
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/cb8e43d456a863e954f6b97a4a821f41d4280ab8/examples/complete-alb/main.tf#L82-L98

1. Define more than one target groups
2. Define an `http_tcp_listeners` block with multiple weighted `target_groups`
3. See terminal output and screenshots below

## Expected behavior

When more than one `target_groups` is defined, `target_group_arn` should be `null`

## Actual behavior

When more than one `target_groups` is defined, `target_group_arn` is still defined, essentially making the listener rule forward traffic to a single target group. 

It's worth mentioning that Terraform doesn't error

### Terminal Output Screenshot(s)

This is how my terraform plan looks like. Notice how both the `target_group_arn` and the multiple `target_group`s are defined
```
      + default_action {
          + target_group_arn = "arn:aws:elasticloadbalancing:us-east-1:012345678912:targetgroup/MY-TARGET-GROUP-1/x0x0x0x0x0x0x"

          + forward {
              + stickiness {
                  + duration = 3600
                  + enabled  = true
                }

              + target_group {
                  + arn    = "arn:aws:elasticloadbalancing:us-east-1:012345678912:targetgroup/MY-TARGET-GROUP-1/x0x0x0x0x0x0x"
                  + weight = 100
                }
              + target_group {
                  + arn    = "arn:aws:elasticloadbalancing:us-east-1:012345678912:targetgroup/MY-TARGET-GROUP-2/x0x0x0x0x0x0x"
                  + weight = 0
                }
            }
        }
```

This results in the target group looking like this

![image](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/13739520/11c27802-5c58-472e-9acc-21d617df89a3)

When the expected behavior is for it to look like this

![image](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/13739520/7b487b1b-cf30-403d-a218-1a6ddef52eaa)

**Comment by antonbabenko** [comment]
This issue has been resolved in version 9.0.0 :tada:
