### ISSUE TITLE
getting Invalid index while crearing alb with huge #  of listener rules

### ISSUE THREAD

**Issue by kiransharma2016** [terraform-aws-modules/terraform-aws-alb#301]
## Description
When the alb is run with  a huge # of listener rules specially, it fails with these errors. 

Error: Invalid index
│
│   on ../terraform-aws-alb/main.tf line 285, in resource "aws_lb_listener_rule" "https_listener_rule":
│  285:       target_group_arn = aws_lb_target_group.main[lookup(action.value, "target_group_index", count.index)].id
│     ├────────────────
│     │ action.value is object with 3 attributes
│     │ aws_lb_target_group.main is tuple with 45 elements
│     │ count.index is 52
│
│ The given key does not identify an element in this collection value.
╵
I am using the input file as in example, defined https_listeners[]. http_tcp_listeners[], and their respective listener rules, and target as a list of map target_group[ [{},{}]

**Comment by not-ajay** [comment]
Hello @kiransharma2016 , I am also facing similar issue while adding multiple rules under httP_tcp_listener_rules, any solution you found ?

**Comment by kiransharma2016** [comment]
Yes, but I like official solutions. Lets see they responde us.  if they wish I can craete  a pr and update the module

**Comment by not-ajay** [comment]
Can you suggest the changes you made ? @kiransharma2016

**Comment by kiransharma2016** [comment]
@not-ajay I  am still looking for official response. Lets wait. I am also validating my solution.

**Comment by bryantbiggs** [comment]
>I am still looking for official response

Without following the information requested in the issue, it will be nearly impossible to help troubleshoot or provide guidance

**Comment by kiransharma2016** [comment]
@bryantbiggs did not see a format. could you plesae give me that. 
I listed the error and line # of the code.

**Comment by kiransharma2016** [comment]
Here is the details
============
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:

- Terraform version:

  terraform version 1.5.3

- Provider version(s):
hashicorp/aws v5.12.0
hashicorp/null v3.2.1


## Reproduction Code [Required]



Steps to reproduce the behavior:

 Not initially. Yes after initial debug is completed. I am getting error in initial phase. 
 no


I prepare a input file the alb module and execute. 

## Expected behavior



should produe  a clean plan report.

## Actual behavior


Plan fails with this error
 on ../terraform-aws-alb/main.tf line 713, in resource "aws_lb_listener" "frontend_https":
│  713:       target_group_arn = contains([null, "", "forward"], lookup(default_action.value, "action_type", "")) ? aws_lb_target_group.main[lookup(default_action.value, "target_group_index", count.index)].id : null
│     ├────────────────
│     │ aws_lb_target_group.main is tuple with 3 elements
│     │ count.index is 4
│     │ default_action.value is object with 5 attributes
│
│ The given key does not identify an element in this collection value.

### Terminal Output Screenshot(s)


the error varies. sometime I get in https_listener rules as I listed in my first post someeimtin tg and sometime here.
## Additional context

**Comment by bryantbiggs** [comment]
>Reproduction Code [Required]

**Comment by antonbabenko** [comment]
This issue has been resolved in version 9.0.0 :tada:
