### ISSUE TITLE
Support for network load balancer (NLB) security groups

### ISSUE THREAD

**Issue by spr-mweber3** [terraform-aws-modules/terraform-aws-alb#304]
Official announcement from AWS can be fond [here](https://aws.amazon.com/about-aws/whats-new/2023/08/network-load-balancer-supports-security-groups/).

The [functionality](https://github.com/hashicorp/terraform-provider-aws/issues/32982) has been added to the AWS provider in [v5.13](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.13.0) if I understood that right. At least something about this new feature can be found in the release notes.

While https://github.com/hashicorp/terraform-provider-aws/pull/33008 states that no implementation updates were need. So there is a good possibility it already should work with pre-v5.13 releases of the provider.

**Comment by bryantbiggs** [comment]
correct - it should "just work" if you upgrade to the latest provider version.

**Comment by spr-mweber3** [comment]
That's what I figured as well. In that case it's just this module here, that also needs to start supporting that. Currently [main.tf#L13](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/main.tf#L13) and [main.tf#L803](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/main.tf#L803) indicate, that it's not supported yet.

**Comment by spr-mweber3** [comment]
.keep

**Comment by antonbabenko** [comment]
This issue has been resolved in version 9.0.0 :tada:
