### ISSUE TITLE
Creating TCP based target_group wrongly sets backend_protocol to HTTP with path = '/'

### ISSUE THREAD

**Issue by lnkrishnan** [terraform-aws-modules/terraform-aws-alb#306]
## Description

We have a requirement to setup an internal NLB listening on port 8420, forwarding to a set of IPs that are outside the VPC range, on same port.

When created via CloudFormation (template provided below), the target_group's health check settings are set to the following - this is the expected behavior:
```
Protocol: TCP
Timeout: 10 seconds
Port: Traffic Port
Interval: 30 seconds
Healthy Threshold: 3 consecutive health check failures
Unhealthy Threshold: 3 consecutive health check failures
```

However, when setting up the NLB and target_group using the terraform (code provided below), the target_group's health check settings are set to the following:
```
Protocol: HTTP
Path: "/"
Timeout: 10 seconds
Port: Traffic Port
Interval: 30 seconds
Healthy Threshold: 3 consecutive health check failures
Unhealthy Threshold: 3 consecutive health check failures
```

- [ X ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version: 8.7.0

- Terraform version: 1.5.7
- Provider version(s): `registry.terraform.io/hashicorp/aws v4.67.0`

## Reproduction Code

Cloudformation template:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Sets up Internal NLB and Target Group

Resources:
  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: MyTargetGroup
      HealthCheckIntervalSeconds: 10
      HealthCheckProtocol: TCP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 3
      Port: 8420
      Protocol: TCP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '120'
      TargetType: ip
      Targets:
        - AvailabilityZone: all
          Id: "10.100.10.100"
          Port: 8420
        - AvailabilityZone: all
          Id: "10.100.10.200"
          Port: 8420
      UnhealthyThresholdCount: 3
      VpcId: "vpc-951f7f13"

  MyLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: MyLoadBalancer
      Subnets:
        - "subnet-161d7baa"
        - "subnet-951f2050"
        - "subnet-33097f13"
      Scheme: internal
      Type: network
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: load_balancing.cross_zone.enabled
          Value: 'true'
      Tags:
        - Key: Name
          Value: MyLoadBalancer

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: MyLoadBalancer
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 8420
      Protocol: TCP
```

Terraform code:
```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.67.0"
    }
  }
}

provider "aws" {
  region = "ap-southeast-1"
}

module "nlb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "~> 5.0"

  name = "my-nlb"

  load_balancer_type = "network"
  internal           = true

  vpc_id  = "vpc-951f7f13"
  subnets = ["subnet-161d7baa", "subnet-951f2050", "subnet-33097f13"]

  target_groups = [
    {
      name_prefix                       = "sfg-"
      backend_protocol                  = "TCP"
      backend_port                      = 8420
      target_type                       = "ip"
      deregistration_delay              = 120
      load_balancing_cross_zone_enabled = true
      health_check = {
        enabled             = true
        interval            = 30
        port                = "traffic-port"
        healthy_threshold   = 3
        unhealthy_threshold = 3
        timeout             = 10
      }

      targets = {
        ip_address_1 = {
          target_id         = "10.100.10.100"
          port              = 8420
          availability_zone = "all"
        },
        ip_address_2 = {
          target_id         = "10.100.10.200"
          port              = 8420
          availability_zone = "all"
        }
      }
    }
  ]

  http_tcp_listeners = [
    {
      port               = 8420
      protocol           = "TCP"
      target_group_index = 0
      action_type        = "forward"
    }
  ]

  tags = {
    Environment = "Test"
  }
}
```

Are you using workspaces? No
Have you cleared the local cache (see Notice section above)? Yes

## Expected behavior

NLB provisioned with target_group's health check settings configuration as outlined below:
```
Protocol: TCP
Timeout: 10 seconds
Port: Traffic Port
Interval: 30 seconds
Healthy Threshold: 3 consecutive health check failures
Unhealthy Threshold: 3 consecutive health check failures
```
Screenshot: ![CFT based NLB](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/11758373/4b43ad59-09d7-4213-8118-385647d01382)

## Actual behavior

target_group's health check settings configuration wrongly set up as outlined below:
```
Protocol: HTTP
Path: "/"
Timeout: 10 seconds
Port: Traffic Port
Interval: 30 seconds
Healthy Threshold: 3 consecutive health check failures
Unhealthy Threshold: 3 consecutive health check failures
```

Screenshot: ![TF Module based NLB](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/11758373/3ababf58-35da-4fbe-af3e-4a69e5f8b348)

**Comment by lnkrishnan** [comment]
Any ideas, anybody?

**Comment by lnkrishnan** [comment]
@bryantbiggs / @antonbabenko any thoughts on this?

**Comment by bryantbiggs** [comment]
this is the default behavior from the AWS API per the spec https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-healthcheckpath

> [HTTP1 or HTTP2 protocol version] The ping path. The default is /.

We do not do anything unique in this module for this, we simply follow the default behavior of the AWS API

**Comment by simoon78** [comment]
Hello, Looks like `backend_protocol` and `backend_protocol` are now `protocol` and `port`. @lnkrishnan  please check:

[port](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-port)

[protocol](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-protocol)
