### ISSUE TITLE
enable_xff_client_port No Longer Defaults to True in AWS Provider

### ISSUE THREAD

**Issue by stewartcampbell** [terraform-aws-modules/terraform-aws-alb#308]
## Description

[enable_xff_client_port](https://registry.terraform.io/providers/hashicorp/aws/5.18.1/docs/resources/lb#enable_xff_client_port) now defaults to `false` in the provider.

I see chat here https://github.com/terraform-aws-modules/terraform-aws-alb/pull/284 about that not being the case previously.

Now they have reverted to the correct setting, the module should reflect that. I appreciate it means another default change, but in my opinion, it is being changed to the correct setting since that is the API default.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
v8.7.0
- Terraform version:
n/a
- Provider version(s):
v5.18.1

## Reproduction Code [Required]

n/a

Use the module without configuring [enable_xff_client_port](https://github.com/terraform-aws-modules/terraform-aws-alb#input_enable_xff_client_port).

## Expected behavior

should default to false

## Actual behavior

defaults to true

### Terminal Output Screenshot(s)

n/a

## Additional context

n/a

**Comment by Jarodiv** [comment]
Thanks for pointing that out, I've created a PR for the change.

**Comment by bryantbiggs** [comment]
this is resolved in #305
