### ISSUE TITLE
Optional log bucket

### ISSUE THREAD

**Issue by alexjurkiewicz** [terraform-aws-modules/terraform-aws-alb#31]
When I try to create an alb with just the seven mandatory variables, I get this error:

```
* aws_alb.main: Failure configuring ALB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
	status code: 400, request id: 266322f3-fa78-11e7-a2c3-ade7d8e52966
```

The problem is that that `access_logs` block of the `aws_alb` resource is always defined, even if you don't specify a bucket name.

I don't believe Terraform's configuration language can support making the `access_logs` block optional, because sub-blocks cannot have a `count` parameter. So the best "workaround" for now is probably just to mark the bucket name as a required parameter, and accept people can't use this module without specifying a log bucket.

**Comment by alexjurkiewicz** [comment]
One note: it is possible to fix this issue by specifying a real bucket for the `bucket_name` parameter... but there is no global "/dev/null" bucket so a real bucket would need to be maintained by the owners of this repo - and they could then read access logs of misconfigured users...

**Comment by brandoconnor** [comment]
This is resolved now. Thanks again for reporting the issue!
