### ISSUE TITLE
Request for contributions - Usage patterns

### ISSUE THREAD

**Issue by bryantbiggs** [terraform-aws-modules/terraform-aws-alb#311]
## Is your request related to a problem? Please describe.

- With the updates in #305 (v9.0), the configurations utilize deeply nested maps which reflect the AWS API. Understanding these maps can be challenging for users so we would like to demonstrate the configurations required for common usage patterns. 

## Describe the solution you'd like.

- If you would like to contribute, please open a pull request to contribute the configuration snippet (we do not need the full module definition, just the relevant bits for the associated usage pattern) adding that pattern to [here](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/docs/patterns.md)

**Comment by cdhesse** [comment]
I believe making use of typed variables (with detailed validations on each field which gives feedback to the developer while trying to use it) would be very beneficial, vs. definitions with type "any".  Is there a reason why this isn't being done?  Is it fear of backwards compatability?

**Comment by bryantbiggs** [comment]
> Is there a reason why this isn't being done?

Yes - the use of fully structured variable definitions have been quite problematic. We have not revisited this with the new optional arguments, but the gain seems to be marginal at best when compared with the overhead and complexity of maintaining such definitions

**Comment by bryantbiggs** [comment]
thanks all for the contributions! If there are additional patterns that are of interest, please feel free to let us know, but for now we'll close out this issue
