### ISSUE TITLE
v9: Incompatibility with `terraform-aws-eks` module - self-managed node groups (`target_group_arns`)

### ISSUE THREAD

**Issue by pat-s** [terraform-aws-modules/terraform-aws-alb#312]
If your request is for a new feature, please use the `Feature request` template.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 9.0.0

- Terraform version: 1.5.7

- Provider version(s): `+ provider registry.terraform.io/hashicorp/aws v5.23.1`

## Reproduction Code [Required]

`terraform-aws-eks` v19 expects a list of strings for the `target_group_arns` variable

https://github.com/terraform-aws-modules/terraform-aws-eks/blob/51cc6bec880ac8dc361b60a4b05d5f2bcd98eb6a/modules/self-managed-node-group/variables.tf#L401-L405 

https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/self-managed-node-group#input_target_group_arns

This worked so far but after `alb/nlb` switched to maps, this now fails with

```
│ Error: Invalid value for input variable
│ 
│   on .terraform/modules/cluster_prod.cluster/node_groups.tf line 411, in module "self_managed_node_group":
│  411:   target_group_arns         = try(each.value.target_group_arns, var.self_managed_node_group_defaults.target_group_arns, [])
│ 
│ The given value is not suitable for module.cluster_prod.module.cluster.module.self_managed_node_group["base_small"].var.target_group_arns declared at
│ .terraform/modules/cluster_prod.cluster/modules/self-managed-node-group/variables.tf:401,1-29: list of string required.
```

## Expected behavior

Works OOB.

## Actual behavior

Fails with error.

## Additional context

The changelog could be updated with a note that the new `target_group_arns` output is a map and must be coerced to a list for other modules to work with it. (or state that other modules might also switch to maps in the next major and one should wait to update).

(NB: while writing this, I haven't yet found out how to do so programmatically, i.e. address the correct child object. I used hardcoded values as a workaround for now).

**Comment by bryantbiggs** [comment]
You can just iterate over the output of `target_groups` and extract the values you wish to use, such as:

```hcl
locals {
  target_group_arns = [for k,v in module.alb.target_groups: v.arn]
}
```

**Comment by bryantbiggs** [comment]
closing with solution provided above
