### ISSUE TITLE
guidance - ECS Fargate + CodeDeploy changes in target groups

### ISSUE THREAD

**Issue by mdimarino** [terraform-aws-modules/terraform-aws-alb#322]
Hello, I would like a guidance on how to proceed using this ALB module on how to handle changes made by CodeDeploy during a Blue/Green deployment for an ECS Fargate service.

Initially ECS Fargate uses 2 target groups with different weights, usually one with 100% of traffic and other with 0%. Lets call them tg-a and tg-b respectivelly. When CodeDeploy starts a new deploy for this service it creates tasks on tg-b, increases its traffic to 100% and finally removes tg-a.

This creates a configuration drift when we run terraform again, lets says to create new rules.

Is there a way in this module to ignore target group, and rule, changes made by CodeDeploy?

Thanks for your amazing work in this module!

**Comment by smailc** [comment]
I have having the same issue. Decoupling IaC from CICD must be a common use-case.

**Comment by sebboh** [comment]
+1 for this feature

I came in here looking for the same thing and found this helpful workaround posted in a similar closed issue: https://github.com/terraform-aws-modules/terraform-aws-alb/issues/219#issuecomment-1229595014

I created my target groups and listener outside of the module and it seems to be working. after a blue/green deploy, terraform plan does not show any changes

**Comment by bryantbiggs** [comment]
please open an issue here https://github.com/aws-ia/ecs-blueprints

**Comment by siourdas-vasilis** [comment]
+1
