### ISSUE TITLE
aws_lb_target_group_attachment is broken after upgrade to 9.x version. Also, strange error showing up, related to default_action for aws_lb_listener resource.

### ISSUE THREAD

**Issue by Andrei-sys** [terraform-aws-modules/terraform-aws-alb#323]
I have the following listener declared:
```
  listeners = {
    http-listener-443 = {
      port            = 443
      protocol        = "HTTPS"
      certificate_arn = var.ssl_certification_arn
      default_action = {
        type         = "fixed-response"
        status_code  = "501"
        content_type = "text/plain"
        message_body = "No Path Found"
      }
      rules = {
        forward = {
          priority = 1
          actions = [
            {
              type             = "forward"
              target_group_key = "target-8081"
            }
          ]

          conditions = [
            {
              path_patterns = ["/*"]
            }
          ]
        }
  }
```
In terraform plan I get the following errors:
 Error: Insufficient default_action blocks
│ 
│   on .terraform/modules/alb.alb/main.tf line 70, in resource "aws_lb_listener" "this":
│   70: resource "aws_lb_listener" "this" {
│ 
│ At least 1 "default_action" blocks are required.

===========================================================
Question1:
Why is this happening because I have added default_action for the listener?

===========================================================

And the second error message is this, related to LB target group attachment:
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/alb.alb/main.tf line 511, in resource "aws_lb_target_group_attachment" "this":
│  511:   target_id         = each.value.target_id
│     ├────────────────
│     │ each.value is object with 5 attributes
│ 
│ This object does not have an attribute named "target_id".
Question2:
Is this related to the breaking changes? How should we fix it in order to keep same configuration as we did for 8.x module version.

**Comment by Andrei-sys** [comment]
#321 one of my errors is related to this.

**Comment by trevorrea** [comment]
Can you format your code in as it's impossible to read. From what I can read it looks completely wrong and nothing like the example at https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-9.0.md#after-v9x. 

The format should be something like:-

 ```
  listeners = {
    default = {
      port               = 443
      protocol           = "HTTPS"
      certificate_arn    = var.ssl_certification_arn
      fixed_response = {
        status_code = "501"
        content_type = "text/plain"
        message_body = "No Path Found"
      }
      rules = {
        forward = {
          priority = 1
          actions = [
            {
              type = "forward"
              target_group_key = "frontend"
            }
          ]
          conditions = [{
            path_pattern = {
              values = ["/*"]
            }
          }]
        }
      }
    }
  }
```

Having a path pattern of 8.8.8.8 makes no sense. It needs to be an actual path.

**Comment by trevorrea** [comment]
For your second question you'll need to actually include your target group definition for anybody to be able to help with that question but the error is very clear. target_id is required and your target group definition doesn't include it.

**Comment by Andrei-sys** [comment]
Hello, thank you for your answer. This is a snippet that maybe could help you understand better what is my current configuration. Added that default part as stated into the docs but no luck.
I see that in the docs you send me, the target groups are added under listener parameter, but here https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest there is separate, and this is where I took example from.
```
  target_groups = {
    target-8081 = {
      name_prefix      = "broadcast"
      backend_protocol = "HTTP"
      backend_port     = 8081
      target_type      = "ip"
      health_check = {
        path                = "/health"
        port                = 8081
        protocol            = "HTTP"
        healthy_threshold   = 2
        unhealthy_threshold = 5
        interval            = 30
        timeout             = 5
        matcher             = "200"
      }
    }
  }
  listeners = {
    default = {
      port         = 80
      protocol     = "HTTP"
      type         = "fixed-response"
      status_code  = "501"
      content_type = "text/plain"
      message_body = "No Path Found"
    }

    http-listener-443 = {
      port            = 443
      protocol        = "HTTPS"
      certificate_arn = var.ssl_certification_arn
      rules = {
        forward = {
          priority = 1
          actions = [
            {
              type             = "forward"
              target_group_key = "target-8081"
            }
          ]

          conditions = [
            {
              path_patterns = ["/*"]
            }
          ]
        }
```

**Comment by trevorrea** [comment]
You need to change your listeners and target_groups to match the docs and what I've given you. What you've pasted is clearly in the wrong format.

I'm sorry I'm just another user of this module so I'm not really prepared to spend time writing this for you.  

My comment at https://github.com/terraform-aws-modules/terraform-aws-alb/issues/321#issuecomment-1803675017 may help you.

**Comment by Andrei-sys** [comment]
I managed to get rid of the target_id error. Still trying to figure out about the one with default_action, as I have added that section to the listeners.

**Comment by bryantbiggs** [comment]
> but here [registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest](https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest) there is separate, and this is where I took example from.

If you are using the resources directly, then this would be applicable. However, if you are using this module, then you should refer to the documentation and examples provided by the module

**Comment by Andrei-sys** [comment]
But if I take a look on this example: https://github.com/terraform-aws-modules/terraform-aws-alb/blob/v9.1.0/examples/complete-alb/main.tf there is no default action for any listener. That's quite confusing.

**Comment by bryantbiggs** [comment]
These are all default actions - this is the default behavior when the listener rule does not specify an action:
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L67
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L143
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L160
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L174
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L274
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3289f9ff8ea2d16a3e39c67e582f4fab236ca5b9/examples/complete-alb/main.tf#L329

**Comment by trevorrea** [comment]
Bryant has linked to the relevant docs and examples so everything is there if you're prepared to read it which it seems you are not. 

Anyway..I haven't tested this but based on what I think you're trying to do you need something like this.  If you're forwarding all traffic you don't need actually need a rule at all. Just use the foward action to your target group.

```
target_groups = {
  target-8081 = {
    name_prefix      = "broadcast"
    backend_protocol = "HTTP"
    backend_port     = 8081
    target_type      = "ip"
    health_check = {
      path                = "/health"
      port                = 8081
      protocol            = "HTTP"
      healthy_threshold   = 2
      unhealthy_threshold = 5
      interval            = 30
      timeout             = 5
      matcher             = "200"
    }
    # Theres nothing to attach here in this definition. Instead,
    # ECS will attach the IPs of the tasks to this target group
    create_attachment = false
  }
}

listeners = {
  http = {
    port         = 80
    protocol     = "HTTP"
    fixed-response = {
      status_code  = "501"
      content_type = "text/plain"
      message_body = "No Path Found"
    }
  }
  https = {
    port            = 443
    protocol        = "HTTPS"
    certificate_arn = var.ssl_certification_arn
    forward = {
      target_group_key = "target-8081"
    }
  }
}
```

**Comment by Andrei-sys** [comment]
Thank you @bryantbiggs ! What you suggested really helped. @trevorrea please don't reploy on issues if you are that kind of toxic person. That does not make you a genuine professional, but thank you for trying to help me as well.

**Comment by Andrei-sys** [comment]
Issue solved
