### ISSUE TITLE
NLB subnet configuration example not idempotent

### ISSUE THREAD

**Issue by johnbarney** [terraform-aws-modules/terraform-aws-alb#325]
## Description

Module or example not idempotent (not sure which yet)

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 9.2.0

- Terraform version: 1.6.4

- Provider version(s): 5.26.0

## Reproduction Code [Required]

Example code in module repo

terraform init
terraform apply
(wait for success)
terraform apply

Fresh clone of your repo, no workspaces or outside code used.

## Expected behavior

Expect the module and the example code to be idempotent

## Actual behavior

NLB and all listeners are recreated every apply without code changes causing downtime on every terraform apply regardless of code changes to the module configuration

### Terminal Output Screenshot(s)

<img width="1273" alt="Screenshot 2023-11-20 at 11 57 57 AM" src="https://github.com/terraform-aws-modules/terraform-aws-alb/assets/1023415/71f34d76-88c0-4063-8f3b-b15ea4fb7b8f">

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/17281#issuecomment-1641980881

**Comment by bryantbiggs** [comment]
The upstream provider linked issue has been corrected - please retry after updating to use the version where it was fixed
