### ISSUE TITLE
Bug - Multiple conditions not supported in load balancer rule

### ISSUE THREAD

**Issue by cdhesse** [terraform-aws-modules/terraform-aws-alb#328]
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/7ed6f047d37510f60c866efc984757fc6b660007/main.tf#L343C3-L343C11

Currently, multiple conditions, such as path_pattern and host_header together, generate a single condition block, which gives the error 
"Only one of host_header, http_header, http_request_method, path_pattern, query_string or source_ip can be set in a condition block"

This should look like this - taken from the terraform aws provider documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule

```
resource "aws_lb_listener_rule" "static" {
  listener_arn = aws_lb_listener.front_end.arn
  priority     = 100

  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.static.arn
  }

  condition {
    path_pattern {
      values = ["/static/*"]
    }
  }

  condition {
    host_header {
      values = ["example.com"]
    }
  }
}
```

**Comment by bryantbiggs** [comment]
please provide the details required in the supplied issue template
