### ISSUE TITLE
Multiple conditions in load balancer rules throw the error "Only one of host_header, http_header, http_request_method, path_pattern, query_string or source_ip can be set in a condition block"

### ISSUE THREAD

**Issue by cdhesse** [terraform-aws-modules/terraform-aws-alb#329]
## Description

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/7ed6f047d37510f60c866efc984757fc6b660007/main.tf#L343C3-L343C11

Currently, multiple conditions, such as path_pattern and host_header together, generate a single condition block, which gives the error
"Only one of host_header, http_header, http_request_method, path_pattern, query_string or source_ip can be set in a condition block"

This should look like this - taken from the terraform aws provider documentation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener_rule

```
resource "aws_lb_listener_rule" "static" {
  listener_arn = aws_lb_listener.front_end.arn
  priority     = 100

  action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.static.arn
  }

  condition {
    path_pattern {
      values = ["/static/*"]
    }
  }

  condition {
    host_header {
      values = ["example.com"]
    }
  }
}
```

- [ x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 9.2.0
- Terraform version: 1.5.5

- Provider version(s): 5.26.0

## Reproduction Code [Required]

 No
 Yes
 terraform plan, terraform apply

## Expected behavior

Multiple conditions in listener rules should work as expected

## Actual behavior

Multiple conditions render incorrectly as a single condition block

**Comment by bryantbiggs** [comment]
do you have a reproduction?

**Comment by cdhesse** [comment]
> I don't need the example that we provide, I just need a minimal reproducible example and a detailed explanation of what is trying to be accomplished, steps to reproduce, and the current result vs the expected result. Jumping straight into the code or suggested fixes tend to lead to these long back and forths because the proper details weren't provided from the beginning so that we can properly triage and troubleshoot

How is what i provided not meeting this request?  If you use the example I provided, do terraform plan, terraform apply, you will see the error I indicated in the bug report.  

What I'm trying to accomplish:
create a listener rule with multiple conditions


If you want JUST the code snippet, it's the below from the example... it's "any multiple condition in any rule"...


  rules = {
        ex-fixed-response = {
          priority = 3
          actions = [{
            type         = "fixed-response"
            content_type = "text/plain"
            status_code  = 200
            message_body = "This is a fixed response"
          }]
          conditions = [{
            host_header = {
              values = ["foobar.com"]
            }
            http_header = {
              http_header_name = "x-Gimme-Fixed-Response"
              values           = ["yes", "please", "right now"]
            }
          }]
        }
      }

**Comment by bryantbiggs** [comment]
Now we're cookin with Crisco! 

Your syntax is incorrect - you are passing a single map to `conditions` but should be passing multiple maps like:

```hcl
      rules = {
        ex-fixed-response = {
          priority = 3
          actions = [{
            type         = "fixed-response"
            content_type = "text/plain"
            status_code  = 200
            message_body = "This is a fixed response"
          }]

          conditions = [
            {
              host_header = {
                values = ["foobar.com"]
              }
            }, 
            {
              http_header = {
                http_header_name = "x-Gimme-Fixed-Response"
                values           = ["yes", "please", "right now"]
              }
            }
          ]
        }
```

Here is the result from the console after applying:
![image](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/10913471/96e35449-b9c0-4f09-97be-b1ecc00e8130)
