### ISSUE TITLE
9.0 upgrade issue: Insufficient default_action blocks 

### ISSUE THREAD

**Issue by dougbergh** [terraform-aws-modules/terraform-aws-alb#330]
## Description

I don't know whether this is a bug or pilot error...I see no way to ask a question other than submitting an issue here. Sorry if it's inappropriate, and please let me know if there's a better way.

I am upgrading from 8.x to 9.2. I followed the upgrade guide but I am getting the following issue:

Error: Insufficient default_action blocks
│ 
│   on .terraform/modules/alb/main.tf line 76, in resource "aws_lb_listener" "this":
│   76: resource "aws_lb_listener" "this" {
│ 
│ At least 1 "default_action" blocks are required.
╵

I don't see how to add a `default_action`.

## Versions

- Module version [Required]: 9.2

- Terraform version:
Terraform v1.6.5
- Provider version(s):
Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/elastic/ec v0.8.0
+ provider registry.terraform.io/hashicorp/aws v5.28.0

## Reproduction Code [Required]

```hcl
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "~> 9.2"

  name = "${local.name}-lb"

  load_balancer_type = "application"

  vpc_id          = var.vpc_id
  subnets         = var.public_subnets
  security_groups = [module.alb_sg.security_group_id]

  listeners = {
    default = {
      port        = 80
      protocol    = "HTTP"
      action_type = "redirect"
      redirect    = {
        port        = var.container_definitions.port
        protocol    = "HTTPS"
        status_code = "HTTP_301"
      }
    },
    https_forward = {
      port               = tonumber(var.container_definitions.port)
      protocol           = "HTTPS"
      certificate_arn    = var.cert_resources["${var.cert_resource_default_domain}"].acm_certificate_arn
      target_group_index = 0
      rules = {
        forward = {
          priority             = 1
          actions = [
            {
              type               = "forward"
              target_group_index = 0
            }
          ]
          conditions = [{
            path_patterns = ["*"]
          }]
        }

      }
    }
  }

  target_groups = [
    {
      name             = "${local.container_name}-${var.container_definitions.port}-tg"
      backend_protocol = "HTTP"
      backend_port     = tonumber(var.container_definitions.port)    # nginx routes http on 443 properly
      target_type      = "ip"
      health_check     = {
        matcher = "200,301,302"
      }
    }
  ]

  tags = local.tags
}
```

 NO
 YES

I'm using terragrunt.

terragrunt plan --terragrunt-source ~/dev/terraform-modules//ecs-ec2-autoscaling

## Expected behavior

no errors, alb created

## Actual behavior

error shown above

**Comment by bryantbiggs** [comment]
your target group is missing the default action - see [here](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/docs/patterns.md#target-groups) for examples, usually its forwarding to an instance, IP, ASG, etc.

**Comment by ragerdevops** [comment]
Good afternoon, I am in the same error as @dougbergh, I have been able to create the alb with my requirements but the only thing that is not working for me is the listener, I need to make a forward towards a target group as a default action, I have tried to follow the examples that you comment but without success.
 example 1: 
   listeners = {
     http_weighted_target = {
       port = 80
       protocol = "HTTP"
       weighted_forward = {
         target_groups = [
           {
             target_group_arn = "ARN"
           }
         ]
       }
     }
   }
example 2: 
listeners = {
http_forward = {
       port = 80
       protocol = "HTTP"
       rules = {
         forward = {
           priority = 1
           actions = [
             {
               type = "forward"
               target_group_arn = "ARN"
             }
           ]
           conditions = [{
             path_patterns = ["*"]
           }]
         }
       }
}
}
example 3:
   listeners = {
     alb_listener = {
       port = 80
       action_type = "forward"
       protocol = "HTTP"
       rules = {
         forward = {
         target_group_arn = "ARN"
         type = "forward"
       }
     }
   }
  }

The error I get with all of them is the same, │ At least 1 "default_action" blocks are required.

I don't know if I'm leaving something out or it wouldn't be covered in the module.

**Comment by bryantbiggs** [comment]
please follow the issue template and provide a reproduction - without a reproduction, its nearly impossible to assist

**Comment by ragerdevops** [comment]
## Description

I have been able to create the alb with my requirements but the only thing that is not working for me is the listener, I need to make a forward towards a target group as a default action, I have tried to follow the examples that you comment but without success.

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: latest

- Terraform version: 
 Terraform v1.5.7
- Provider version(s): Terraform v1.5.7 on darwin_arm64

- provider registry.terraform.io/hashicorp/aws v5.26.0

## Reproduction Code [Required]

```
module "alb" {
  source = "terraform-aws-modules/alb/aws"
  name    = var.name
  load_balancer_type = var.load_balancer_type
  vpc_id  = var.vpc_id
  subnets = var.subnets
    security_group_ingress_rules = {
    all_http = {
      from_port   = 80
      to_port     = 80
      ip_protocol = "tcp"
      description = "HTTP web traffic"
      cidr_ipv4   = "0.0.0.0/0"
    }
  }
  security_group_egress_rules = {
    all = {
      ip_protocol = "-1"
      cidr_ipv4   = "0.0.0.0/0"
    }
  }
  listeners = {
    alb_listener = {
      port = 80
      action_type = "forward"
      protocol = "HTTP"
      rules = {
        forward = {
        target_group_arn = var.target_group_arn
        type             = "forward"
      }
    }
  }
 }
  target_groups = {    
    ex_ip = {
      name                              = var.name
      protocol                          = "HTTP"
      port                              = 80
      target_type                       = "ip"
      deregistration_delay              = 5
      load_balancing_cross_zone_enabled = true
      vpc_id                             = var.vpc_id

      health_check = {
        healthy_threshold = "3"
        interval = "30"
        protocol = "HTTP"
        matcher = "200"
        timeout = "3"
        path = "/"
        unhealthy_threshold = "2"
      }
    }
  }
}
```
Steps to reproduce the behavior:

 
NO
 
YES
 

As I mentioned in the previous comment, I have tried to rely on the templates you provide to generate the listeners, but still the same error continues.


Try 1: 

```
   listeners = {
     http_weighted_target = {
       port = 80
       protocol = "HTTP"
       weighted_forward = {
         target_groups = [
           {
             target_group_arn = "ARN"
           }
         ]
       }
     }
   }
```
try 2:

```
listeners = {
http_forward = {
       port = 80
       protocol = "HTTP"
       rules = {
         forward = {
           priority = 1
           actions = [
             {
               type = "forward"
               target_group_arn = "ARN"
             }
           ]
           conditions = [{
             path_patterns = ["*"]
           }]
         }
       }
}
}
```
Try 3

```
   listeners = {
     alb_listener = {
       port = 80
       action_type = "forward"
       protocol = "HTTP"
       rules = {
         forward = {
         target_group_arn = "ARN"
         type = "forward"
       }
     }
   }
  }
```
## Expected behavior

Creation of an alb with its listener making a forward to the target group.

## Actual behavior

Plan: 38 to add, 0 to change, 0 to destroy.
╷
│ Error: Insufficient default_action blocks
│ 
│   on .terraform/modules/alb/main.tf line 76, in resource "aws_lb_listener" "this":
│   76: resource "aws_lb_listener" "this" {
│ 
│ At least 1 "default_action" blocks are required.

### Terminal Output Screenshot(s)

Plan: 38 to add, 0 to change, 0 to destroy.
╷
│ Error: Insufficient default_action blocks
│ 
│   on .terraform/modules/alb/main.tf line 76, in resource "aws_lb_listener" "this":
│   76: resource "aws_lb_listener" "this" {
│ 
│ At least 1 "default_action" blocks are required.

## Additional context


However, it should also be noted that if I create the listener from outside the module with the following code, the whole thing works perfectly:
```
resource "aws_alb_listener" "alb-listener" {
     load_balancer_arn = var.load_balancer_arn
     port = 80
     protocol = "HTTP"
  
     default_action {
       target_group_arn = var.target_group_arn
       type = "forward"
     }
   }
```

**Comment by ragerdevops** [comment]
> ```terraform
> module "alb" {
>   source = "terraform-aws-modules/alb/aws"
> 
>   name = var.name
> 
>   vpc_id  = var.vpc_id
>   subnets = var.subnets
> 
>   security_group_ingress_rules = {
>     all_http = {
>       from_port   = 80
>       to_port     = 80
>       ip_protocol = "tcp"
>       description = "HTTP web traffic"
>       cidr_ipv4   = "0.0.0.0/0"
>     }
>   }
>   security_group_egress_rules = {
>     all = {
>       ip_protocol = "-1"
>       cidr_ipv4   = "0.0.0.0/0"
>     }
>   }
> 
>   listeners = {
>     alb_listener = {
>       port     = 80
>       protocol = "HTTP"
> 
>       forward = {
>         target_group_key = **"ex_ip"**
>       }
>     }
>   }
> 
>   target_groups = {
>     **ex_ip** = {
>       name                              = var.name
>       protocol                          = "HTTP"
>       port                              = 80
>       target_type                       = "ip"
>       deregistration_delay              = 5
>       load_balancing_cross_zone_enabled = true
> 
>       health_check = {
>         healthy_threshold   = "3"
>         interval            = "30"
>         protocol            = "HTTP"
>         matcher             = "200"
>         timeout             = "3"
>         path                = "/"
>         unhealthy_threshold = "2"
>       }
>     }
>   }
> }
> ```

Hello! @bryantbiggsPerfect! Thank you very much for your help, I didn't know what was wrong, I didn't see the direct reference to the target group map.

For my part, you can consider the doubt resolved! :)
