### ISSUE TITLE
Unsupported in GovCloud: dns_record_client_routing_policy

### ISSUE THREAD

**Issue by LeaderXFX** [terraform-aws-modules/terraform-aws-alb#333]
## Description

GovCloud us-east-1 does not yet support dns_record.client_routing_policy on Network load balancers.

```terraform
Error: failure configuring LB attributes: InvalidConfigurationRequest: Load balancer attribute key 'dns_record.client_routing_policy' is not supported on load balancers with type 'network'
```

Recommend allowing dns_record_client_routing_policy to be set to null until GovCloud supports dns_record.client_routing_policy.

Terraform Version: 1.6.4
Provider Version: 5.30.0

**Comment by bryantbiggs** [comment]
it is set to null https://github.com/terraform-aws-modules/terraform-aws-alb/blob/7339d02f5aabeefd8416bc8a02dade90a7fb2be3/variables.tf#L38
