### ISSUE TITLE
target_id error 

### ISSUE THREAD

**Issue by alok165** [terraform-aws-modules/terraform-aws-alb#336]
│

while using the module alb:

module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "9.4.0"

........ and so on ........

}

I'm getting bellow error with target_id

 Error: Unsupported attribute
│
│   on .terraform\modules\alb\main.tf line 527, in resource "aws_lb_target_group_attachment" "this":
│  527:   target_id         = each.value.target_id
│     ├────────────────
│     │ each.value is object with 5 attributes
│
│ This object does not have an attribute named "target_id".

╵

**Reference Code and resource details are:**
resource "aws_autoscaling_attachment" "asg_attachment_bar" {
  autoscaling_group_name = module.eks.node_groups["eks_nodes"].resources[0].autoscaling_groups[0].name
  lb_target_group_arn    = module.alb.target_groups["ex-instance"].arn
}

**Comment by alok165** [comment]
As per my understanding :The target_id attribute is optional and is typically used when I want to register specific targets with the target group. I'm using Auto Scaling Group (ASG), and don't think I need to provide a target_id because the ASG will automatically register its instances with the target group..

But still get this error with target_id

**Comment by bryantbiggs** [comment]
Without a reproduction we won't be able to help much, if at all

**Comment by bryantbiggs** [comment]
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/docs/patterns.md#target-group-without-attachment

Use with Autoscaling module: https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/62b879b2f87cdee50cfa853571a372996b75c995/examples/complete/main.tf#L51

Use with ECS module: https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/ccc0d3a0786de98d53857b08663dedf11833d789/examples/fargate/main.tf#L139-L145

Plenty examples and docs all around

**Comment by bryantbiggs** [comment]
closing this for now with the guidance provided above
