### ISSUE TITLE
NLB to ASG target_group_arns

### ISSUE THREAD

**Issue by jpc2350** [terraform-aws-modules/terraform-aws-alb#339]
## Description

With the update to move from lists to maps, you refactored the target_groups and listeners elements within this module from 

`http_tcp_listeners = []` to `listeners= { ex-one= {}}` and changed target_groups from a list to a map, but this has invalidated the ability to pass the arns created from this module into the autoscaling module under target_group_arns and now also requires target groups to have a target_id.

How is it envisaged that you pass a target group arn to the autoscaling module without them being in a list and also how are we to create targets without the target_id populated?

- [ yes ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version: 1.5.4
- Provider version(s): 5.31.0

## Reproduction Code [Required]
```
module "nlb" {
  source  = "terraform-aws-modules/alb/aws"

  name = local.name

  load_balancer_type = "network"

  vpc_id                           = data.terraform_remote_state.vpc_edge.outputs.vpc_id
  enable_cross_zone_load_balancing = true

  subnet_mapping = [for i, eip in aws_eip.this : { allocation_id : eip.id, subnet_id : data.terraform_remote_state.vpc_edge.outputs.vpc.public_subnets[i] }]

  listeners = {
    ex-one = {
      port = SOMEPORT
      protocol = "UDP"
      forward = {
        target_group_key = "ex-one"
      }
    }
  }

  target_groups = {
    ex-one = {
      name             = local.name
      protocol         = "UDP"
      port             = SOMEPORT
      target_type      = "instance"
      health_check = {
        healthy_threshold   = 3
        interval            = 5
        timeout             = 3
        unhealthy_threshold = 2
        port                = 80
        protocol            = "TCP"
      }
    }
  }

  tags = local.tags
}

module "asg" {
  source = "terraform-aws-modules/autoscaling/aws"

  # Autoscaling group
  name            = local.name
  enabled_metrics = []

  min_size                  = 0
  max_size                  = 1
  desired_capacity          = 1
  wait_for_capacity_timeout = 0
  health_check_type         = "EC2"
  vpc_zone_identifier       = data.terraform_remote_state.vpc_edge.outputs.vpc.private_subnets

  target_group_arns = module.nlb.target_groups.ex-one.id

etc
}
```

N/A

## Expected behavior

I expect to be able to pass the arns from the target-group created by the ALB/NLB module into the autoscaling module to target the autoscaling group

## Actual behavior

```
│ Error: Invalid value for input variable
│
│   on main.tf line 156, in module "asg":
│  156:   target_group_arns = module.nlb.target_groups.ex-one.id
│
│ The given value is not suitable for module.asg.var.target_group_arns declared at .terraform/modules/asg/variables.tf:130,1-29: list of string required.

│ Error: Unsupported attribute
│
│   on .terraform/modules/nlb/main.tf line 527, in resource "aws_lb_target_group_attachment" "this":
│  527:   target_id         = each.value.target_id
│     ├────────────────
│     │ each.value is object with 5 attributes
│
│ This object does not have an attribute named "target_id".
```

It will also destroy the listener, but won't create a new listener resource?

**Comment by bryantbiggs** [comment]
> How is it envisaged that you pass a target group arn to the autoscaling module without them being in a list 

Like this https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/62b879b2f87cdee50cfa853571a372996b75c995/examples/complete/main.tf#L51

> and also how are we to create targets without the target_id populated?

Read the docs
