### ISSUE TITLE
The latest version is not available on terraform registry

### ISSUE THREAD

**Issue by lays147** [terraform-aws-modules/terraform-aws-alb#346]
## Description
Hi! I'm trying to use this module with its latest version of `v9.5.0` but it isn't available at the Terraform Registry:

![image](https://github.com/terraform-aws-modules/terraform-aws-alb/assets/7799231/fe8de665-5558-4431-91b3-707cb938116f)

## Versions

- Module version [Required]: v9.5.0

- Terraform version:

Terraform v1.7.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v5.34.0
+ provider registry.terraform.io/hashicorp/external v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/null v3.2.2

**Comment by bryantbiggs** [comment]
oy, seems to be a lot of new versions being missed by the Terraform registry lately - @antonbabenko

**Comment by antonbabenko** [comment]
Yeah, Terraform Registry has had some issues lately. I have sent support @ hashicorp an email to ask for help.

**Comment by antonbabenko** [comment]
Fixed. It took a few days to talk with the support.
