### ISSUE TITLE
Use named indexes for target groups

### ISSUE THREAD

**Issue by MWEJ** [terraform-aws-modules/terraform-aws-alb#350]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

Yes, any version

## Is your request related to a problem? Please describe.
When removing a target group from within an array of target groups, Terraform tries to reorder the array by re-creating the target groups and destroying the old ones.
However this approach fails with the error message that the target group already exists because Terraform is trying to create a new target group first before destroying the old one.

## Describe the solution you'd like.
I'd like the array of target groups to use named indexes instead of numbered indexes. This way, in the state it will no longer be named as this:

```
module.my-lb-name.aws_lb_target_group.main[0]
module.my-lb-name.aws_lb_target_group.main[1]
module.my-lb-name.aws_lb_target_group.main[2]
module.my-lb-name.aws_lb_target_group.main[3]
module.my-lb-name.aws_lb_target_group.main[4]
module.my-lb-name.aws_lb_target_group.main[5]
module.my-lb-name.aws_lb_target_group.main[6]
```

But instead like this:
```
module.my-lb-name.aws_lb_target_group.main["target-group-aa"]
module.my-lb-name.aws_lb_target_group.main["target-group-bb"]
module.my-lb-name.aws_lb_target_group.main["target-group-cc"]
module.my-lb-name.aws_lb_target_group.main["target-group-dd"]
module.my-lb-name.aws_lb_target_group.main["target-group-ee"]
module.my-lb-name.aws_lb_target_group.main["target-group-ff"]
module.my-lb-name.aws_lb_target_group.main["target-group-gg"]
```

This would prevent Terraform from having to destroy and recreate target groups when new items are added or removed from the list.

## Describe alternatives you've considered.
I haven't considered any other alternatives

## Additional context
Here is more general information about the issue and how to fix it: https://syedrakib.medium.com/the-problem-of-shifting-all-items-in-a-terraform-array-6b54100319c9

**Comment by bryantbiggs** [comment]
we do https://github.com/terraform-aws-modules/terraform-aws-alb/blob/3e9c6cbaf4c1d858c3bbee6f086f0c8ef17522ab/main.tf#L457
