### ISSUE TITLE
Add lifecycle support to module

### ISSUE THREAD

**Issue by mInrOz** [terraform-aws-modules/terraform-aws-alb#352]
Im currently working in a AWS env that is managed by the AWS LZA (Landing Zone Accelerator).
Where I have a config rule to enable logging on all Load Balancers that is deployed.

The current workflow is so that logging is not specified in Terraform as this is handled by AWS Config / SSM.
This however causes unnecessary changes to the resource each time the TF code is applied, as there is a difference between the resource deployed and specified in TF code.

Because of this i propose adding the capability of defining a lifecycle policy to this module.
Instead of having it hardcoded as it currently is in v9.7.0

**Comment by bryantbiggs** [comment]
thats not going to be possible since you cannot use variables within lifecycle blocks to allow users to select which arguments to ignore dynamically
