### ISSUE TITLE
Example code target group data structure invalid

### ISSUE THREAD

**Issue by hustshawn** [terraform-aws-modules/terraform-aws-alb#356]
## Description

Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration (see the `examples/*` directory for references that you can copy+paste and tailor to match your configs if you are unable to copy your exact configuration). The reproduction MUST be executable by running `terraform init && terraform apply` without any further changes.

If your request is for a new feature, please use the `Feature request` template.

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]: 9.7.0

- Terraform version:
v1.6.5
- Provider version(s):
 provider registry.terraform.io/hashicorp/aws v5.39.1

## Reproduction Code [Required]
```

module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "9.7.0"

  name    = "my-alb"
  vpc_id  = "vpc-abcde012"
  subnets = ["subnet-abcde012", "subnet-bcde012a"]

  # Security Group
  security_group_ingress_rules = {
    all_http = {
      from_port   = 80
      to_port     = 80
      ip_protocol = "tcp"
      description = "HTTP web traffic"
      cidr_ipv4   = "0.0.0.0/0"
    }
    all_https = {
      from_port   = 443
      to_port     = 443
      ip_protocol = "tcp"
      description = "HTTPS web traffic"
      cidr_ipv4   = "0.0.0.0/0"
    }
  }
  security_group_egress_rules = {
    all = {
      ip_protocol = "-1"
      cidr_ipv4   = "10.0.0.0/16"
    }
  }

  access_logs = {
    bucket = "my-alb-logs"
  }

  listeners = {
    ex-http-https-redirect = {
      port     = 80
      protocol = "HTTP"
      redirect = {
        port        = "443"
        protocol    = "HTTPS"
        status_code = "HTTP_301"
      }
    }
    ex-https = {
      port            = 443
      protocol        = "HTTPS"
      certificate_arn = "arn:aws:iam::123456789012:server-certificate/test_cert-123456789012"

      forward = {
        target_group_key = "ex-instance"
      }
    }
  }

  target_groups = {
    ex-instance = {
      name_prefix = "h1"
      protocol    = "HTTP"
      port        = 80
      target_type = "instance"
    }
  }

  tags = {
    Environment = "Development"
    Project     = "Example"
  }
}
```

terraform init
terraform plan

## Expected behavior

Run without error, or do not require the `target_id` if I wanna link to an ASG. of course, I will create traffic source from my ASG module.

## Actual behavior

Got error like below

```
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/alb/main.tf line 537, in resource "aws_lb_target_group_attachment" "this":
│  537:   target_id         = each.value.target_id
│     ├────────────────
│     │ each.value is object with 4 attributes
│
│ This object does not have an attribute named "target_id".
```

That's due to lack of `target_id` within target_groups definition. I checked source code from `.terraform/modules/alb/main.tf line 537`, and the target_id is required, and it's stick to a single instance, or a lambda function. But what if I want to bind target group to an autoscaling group instead of a specific instance_id ?

**Comment by bryantbiggs** [comment]
check the docs please, we have documented and provided examples for these scenarios

**Comment by hustshawn** [comment]
even without consider the autoscaling group, the sample code just doesn't work.

**Comment by bryantbiggs** [comment]
- https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/docs/patterns.md#target-group-without-attachment
- https://github.com/terraform-aws-modules/terraform-aws-ecs/blob/master/examples/ec2-autoscaling/main.tf#L167-L232
