### ISSUE TITLE
Multiple Target Groups per ALB

### ISSUE THREAD

**Issue by lnozot** [terraform-aws-modules/terraform-aws-alb#36]
I'm needing to create ALBs with multiple Target Groups (TG).  The back end may and generally is the same port but are configured in my case by different paths in the URL.  I have resources already built by other modules for VPC, security groups, etc. and looking to create ALBs with one or more TGs.

**Comment by sijin** [comment]
@lnozot  - I think you are looking for this: https://www.terraform.io/docs/providers/aws/r/lb_listener_rule.html 
You should have the 'field  = "path-pattern"' for path based routing.

**Comment by brandoconnor** [comment]
@lnozot thanks for the question and kudos on chiming in @sijin, I think you've got the right idea.

@lnozot - If you've got more than one target group, you might want to create the additional TGs outside of what this repo creates. Likewise, the variables exported from this module should be sufficient to create `lb_listener_rule`s for the scenario you outline above. Does that cover what you're trying to do?

**Comment by brandoconnor** [comment]
Hmmm, hoped I'd get an affirmative reply on the resolution but I think we've done our diligence here. Closing the issue unless someone sees an actionable route to resolve this without blowing out the complexity.

**Comment by lnozot** [comment]
@brandoconnor It seems complicated to create one target group with this module and then another with another module and then glue them together where?  The suggestion from @sijin is correct but I didn't want to fork the module to add some detail and multiple target groups.

I'm using this module with the asg, vpc, and security-group modules.  I have an application set that requires a single ALB but has different back-ends that we manually setup to be identified by paths.  I suppose a separate module to just manage TGs could be used but seems so disjointed from the flow.

**Comment by brandoconnor** [comment]
Looks like the boat left without you @lnozot - 😀  I added this feature a couple weeks ago and it's now available in the latest release. The test fixture now gives an example of how it could look on your end: https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/alb_test_fixture/locals.tf#L44-L55

**Comment by sreekanthareddyn** [comment]
@brandoconnor. appreciate your efforts, this is really helpful. Could you please let me know how can we access target_group arns which i need in  listener rules and also for autoscaling attachments.

Thanks,

**Comment by brandoconnor** [comment]
`target_group_arns` are available as outputs:
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/dfdc6e4fc505f3ea9f4833af8c525f117466217d/outputs.tf#L41
