### ISSUE TITLE
One listener, multiple target groups

### ISSUE THREAD

**Issue by shriyo101** [terraform-aws-modules/terraform-aws-alb#374]
## Is your request related to a new offering from AWS?
yes

Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - No 🛑: please wait to file a request until the functionality is avaialble in the AWS provider
  - Yes ✅: please list the AWS provider version which introduced this functionality

## Is your request related to a problem? Please describe.

I was trying to add one listener and wanted to add ips as targets currently I do have that setup done manually, but was not able to achieve it in terraform module v9.9.0

## Describe the solution you'd like.

Able to add a listener pointing to multiple targets.

## Additional context

ex:
     forward = {
        target_group_key = ["t1", "t2"]
      }

**Comment by surry355f1** [comment]
Having the same issue as well. Any traction on this?

**Comment by surry355f1** [comment]
@shriyo101 ,
I managed to achieve something workable for now. It doesn't solve the issue of 1 listener > multiple target groups. But it does solve 1 listener to multiple IPs. Have a look at additional_target_group_attachments:
https://github.com/terraform-aws-modules/terraform-aws-alb/issues/316

Theres an example in the above as well as:
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf

hth

**Comment by shriyo101** [comment]
HI @surry355f1

I did try https://github.com/terraform-aws-modules/terraform-aws-alb/issues/316 but it dint not work as expected. 
Hence raised this ticket..
