### ISSUE TITLE
best way to do multiple listeners

### ISSUE THREAD

**Issue by rojomisin** [terraform-aws-modules/terraform-aws-alb#38]
Great work on this module, really wraps this process easily.
question:
If I have 2 listeners to implement, do I just create the listener and target group pairs separately and attach to the alb arn?

**Comment by jseiser** [comment]
Same issue here, Im not really seeing how to make this work.

I have 3 autoscaling groups, which all list on HTTPS/8081, and HTTP/80.  SSL Cert will be the same for all the HTTPS ports and access is determined with host based routing.  This appears to want to setup a default listener and target group.

**Comment by brandoconnor** [comment]
Hey @rojomisin and @jseiser - Thanks for the interest in this project and explaining what you're trying to do. I think the use case here is common enough to find a viable solution and I have an idea in mind for it. For now, you might be able to create some resources outside of the module and connect them via the outputs from this module... though I'm not 100% sure and you might end up with unused resources from within the module. I have some time off this week to play around with some improvements and this is definitely one of them.

**Comment by brandoconnor** [comment]
Worked through this today and got to the point of successfully defining both listener types (http/tcp, https) as lists of maps to add flexibility. Rereading what you have here, I'm thinking you're also asking for the target groups to be defined in a similar way (as a list of maps that provide config details). I should have that wrapped up in the next day.
