### ISSUE TITLE
Conditionally setting attributes

### ISSUE THREAD

**Issue by evanstoddard23** [terraform-aws-modules/terraform-aws-alb#380]
## Is your request related to a problem? Please describe.
The `try()` function is used extensively throughout this module to evaluate if a key is set. However I find myself in many cases wanting to conditionally set these keys. When setting a key to `null`, it does not result in an error, so the for_each ends up trying to create a block it shouldn't, resulting in an error. 

Here's an example:

```
module "alb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "9.11.0"
  for_each = {...}
  listeners = {
    https = {
      forward = each.value.some_condition ? null : {
        target_group_key = "default"
      }

      fixed_response = each.value.some_condition ? {
        content_type = "text/plain"
        message_body = "Access denied"
        status_code  = "403"
      } : null
...
```

Results in errors like:

```
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/frontends.alb/main.tf line 141, in resource "aws_lb_listener" "this":
│  141:         content_type = default_action.value.content_type
│     ├────────────────
│     │ default_action.value is null
│ 
│ This value is null, so it does not have any attributes.
```

## Describe the solution you'd like.
Maybe these blocks should look something like this to allow for null values?

```
dynamic "default_action" {
  for_each = try([each.value.fixed_response != null ? each.value.fixed_response : (1 / 0)], [])
...
```

## Describe alternatives you've considered.
I haven't been able to think of other ways to handle this gracefully.

**Comment by bryantbiggs** [comment]
> However I find myself in many cases wanting to conditionally set these keys.

Why? This seems like you are trying to re-wrap this module so you'd have to handle that differently

**Comment by bryantbiggs** [comment]
this feels like an x-y type problem so I'm not sure how much guidance I can provide given the narrow context. but in general, 99.9% of the time we've received issues like this - the answer has always been - "you should adjust how you are doing that"

**Comment by evanstoddard23** [comment]
I was able to more or less get around it for what I’m doing, although it’s not pretty. It does seem to me like a valid part of HCL that’s not being properly handled by this module though given [this in the docs](https://developer.hashicorp.com/terraform/language/expressions/types#types) “null is most useful in conditional expressions, so you can dynamically omit an argument if a condition isn't met.”

**Comment by AkshayB-ops** [comment]
Any solution for this?
