### ISSUE TITLE
secgrp that self-references

### ISSUE THREAD

**Issue by celesteking** [terraform-aws-modules/terraform-aws-alb#391]
I'd like to have a secgroup that references itself, much like what you get by default when you use aws UI to create stuff.

```
security_group_ingress_rules = {
    myself = {
      ip_protocol = -1
      referenced_security_group_id = myself.id
      description = "allow traffic from myself secgrp"
    }
}
```

There are no discussions open, so I'm asking here. Thanks.

**Comment by bryantbiggs** [comment]
Why?

**Comment by celesteking** [comment]
It's a stupid idea indeed in relation to an ALB.
