### ISSUE TITLE
Improvement request: New variable for HTTP port listener

### ISSUE THREAD

**Issue by egarbi** [terraform-aws-modules/terraform-aws-alb#40]
Would it be possible to have a new variable (defaulted to 80) to be able to change the port for the HTTP listener for other than 80? 
This is specially useful in my usecase when using this module to create an Internal ALB.
We dont use the default port for internal ones.
If you agree I can create the PR to have it done

**Comment by oddsocksio** [comment]
there appears to be a traffic port mentioned in the documentation appearing as though this feature was intended

**Comment by brandoconnor** [comment]
Hey @egarbi -

I like the idea and am 100% on board with that feature. Send over the PR when you have a chance or I may get to it this week as I have some time off.

@oddsocksio - the port variable you're seeing is `backend_port` which specifies the port that the EC2 hosts in your target group are listening on and serving from. This can differ from the default of port 80 but as @egarbi points out, the ALB's front-end listener only listens from connections on standard ports of 80 and 443 without variable.
