### ISSUE TITLE
access_logs.s3.bucket empty errors

### ISSUE THREAD

**Issue by mbolek** [terraform-aws-modules/terraform-aws-alb#7]
`Failure configuring ALB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
	status code: 400, request id: cd69fceb-bb12-11e7-a276-19494eb0aecb`
I get the above message when I do not set any value for log_bucket. Currently I can see that 'enabled' for access_logs is based on setting the log_bucket:
` access_logs {
    bucket  = "${var.log_bucket}"
    prefix  = "${var.log_prefix}"
    enabled = "${var.log_bucket != ""}"
  }`
 I think it would be better to have this as a separate value (enable_access_logs ?) so it is possible to pass the log_bucket but not enable the access_logs. What do you think about this?

Also, the job failed when setting the log_bucket to a chosen one when it has just been created - I think s3 didn't converge fully before the bucket assignement to ALB - maybe a backoff timer or something. Don't know if terraform actually has something to fix this

**Comment by antonbabenko** [comment]
Agree, PR is always welcome

**Comment by brandoconnor** [comment]
Hey @mbolek . Thanks for the issue submission. Can you show both how the module was called and the output of terraform when this issue happens? Terraform version info would also be helpful.

**Comment by mbolek** [comment]
Sure, here's the module usage:
```hcl
module "alb" {                                                                                                                                                            
  source = "terraform-aws-modules/alb/aws"                                                                                                                                
                                                                                                                                                                          
  alb_is_internal     = "false"                                                                                                                                           
  alb_name            = "${var.alb_name}"                                                                                                                                 
  alb_protocols       = ["${var.alb_protocols}"]                                                                                                                          
  alb_security_groups = "${var.alb_security_groups}"                                                                                                                      
  region              = "${var.aws_region}"                                                                                                                               
                                                                                                                                                                          
  log_bucket = "${var.log_bucket}"                                                                                                                                        
  log_prefix = "${var.log_prefix}"                                                                                                                                        
                                                                                                                                                                          
  backend_port      = "${var.backend_port}"                                                                                                                               
  backend_protocol  = "${var.backend_protocol}"                                                                                                                           
  certificate_arn   = "${var.certificate_arn}"                                                                                                                            
  cookie_duration   = "${var.cookie_duration}"                                                                                                                            
  health_check_path = "${var.health_check_path}"                                                                                                                          
  subnets           = ["${var.subnets}"]                                                                                                                                  
  vpc_id            = "${var.vpc_id}"                                                                                                                                     
  tags              = "${var.tags}"                                                                                                                                       
} 
```

log_prefix has some value, but log_bucket is empty:

```hcl
log_bucket = ""
log_prefix="${var.alb_name}"
```
And here's the output, same as above:
```
Error: Error applying plan:

1 error(s) occurred:

* module.alb.module.alb.aws_alb.main: 1 error(s) occurred:

* aws_alb.main: Failure configuring ALB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
	status code: 400, request id: cd69fceb-bb12-11e7-a276-19494eb0aecb
```
I'm using terraform v0.10.8 and terragrunt 0.13.14

Looking at the TF docs regarding [alb](https://www.terraform.io/docs/providers/aws/r/lb.html). It seems that bucket_name is a required parameter so it probably shouldn't be empty if the entire 'access_logs' block has been added. I'd like to be able to specify all the params but still keep it disabled which is currently impossible since setting log_bucket also sets enabled to true.

I just tested the code from the example dir (small issue with the source of module - it uses '../../../' and I think it's one dir too far) - it works ok, but it has log_bucket and log_prefix set. If I delete both (from examples/test_fixtures/main.tf), I get:
```
* module.alb.aws_alb.main: 1 error(s) occurred:

* aws_alb.main: Failure configuring ALB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
        status code: 400, request id: 7580a60b-bc8f-11e7-8a04-e7ddc10ac001
```
I think defaults come into play then, and log_prefix is set to "my-alb-logs". I tried with removing the default (examples/test_fixtures/variables.tf) and still get the error:
```
* module.alb.aws_alb.main: 1 error(s) occurred:

* aws_alb.main: Failure configuring ALB attributes: ValidationError: The value of 'access_logs.s3.bucket' cannot be empty
        status code: 400, request id: 1bf1992d-bc90-11e7-9665-d7f7044996df
```

Generally, I think that my use case may just be weird - settings vars but disabling access_logs. However, should you consider changing the behaviour (adding variable e.g. enable_access_logs), I can try and create a PR :)

**Comment by brandoconnor** [comment]
Thanks on the details. If I understand you here, there's some value to you in filling out each of those options for logging but still keeping logging disabled. Not a need I would have anticipated but if that's your use-case, let's work with it.

Re: terragrunt - I haven't used terragrunt so I really don't know if this module is compatible there. This module makes no guarantees to work with that tool but given that terragrunt is just a thin wrapper on terraform, I can't imagine that's the source of any issues.

Re: ../../../ : agreed that it it appears to be one dir too far but when running tests via test kitchen, this arrangement is what works (the proper directory location doesn't). Perhaps we have a bug in kitchen-terraform or test-kitchen itself? While validating the test fixture via terraform validate and fmt in CI, I adjust the path using sed in place to what you suggested to get those commands working. So which to chose? I think there's more benefit to keeping test runs more accessible by leaving the path as is. If someone can think of a better way that resolves both, I'm all ears, but interpolations/variables aren't allowed in a source definition so options are significantly limited.

Let me know if you need help on the PR. It's a relatively small change but we're here to help. :dancer:

**Comment by antonbabenko** [comment]
I have a similar problem. I have two ALBs which I want to write logs into the same bucket. Now I can't make it, because "bucket already exists" after first ALB has been created.

**Comment by brandoconnor** [comment]
Interesting. Yea thinking about the case of several ALBs each wanting to talk to the same bucket but likely under different prefixes, it would make more sense to control that bucket outside of this module and in a separate terraform module/set of templates. That likely adds another variable to the mix to determine count of bucket and policy creation. Sound reasonable?

**Comment by antonbabenko** [comment]
Yes, I prefer to make a creation of buckets outside of modules where it is used because then I can set up more granular bucket policies and control lifecycle more precisely. Will you be able to fix it during next week? (I will be using this module in 8 days) :)

**Comment by brandoconnor** [comment]
@antonbabenko Yep, I was waiting to give @mbolek a fair shot at a PR but I can patch it up this over the next day or so. Expect to see a review request early next week at latest.

**Comment by mbolek** [comment]
sorry... took some vay-kay. Regarding terragrunt I don't think it should have an impact on the code. And of course, with "../../" issue, tests are more important.
Besides, since in your main.tf, there is an 'access_log' block already, all the params need to be there or it won't work. I'll work on the PR, unless you'll be faster:)
