### ISSUE TITLE
AWS LB resource created without specifying vpc_id

### ISSUE THREAD

**Issue by jeteon** [terraform-aws-modules/terraform-aws-alb#74]
**Describe the bug**
The `aws_lb` resource is created without explicitly specifying it's VPC ID. This means that even if a VPC ID is specified in the module inputs, the default VPC for the AWS account will be used anyway. 

**To Reproduce**
1. Set up an AWS account and region with 2 VPCs
2. Set VPC 1 to be the default VPC
3. Run this module with the vpc_id set to VPC 2
4. Observe that the associated `alb.aws_lb.application` is created in VPC 1 instead of VPC 2.

**Expected behavior**
All of the resources required for the Application Load Balancer are created with the VPC specified in the input to the module.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.13.5
 - Versions: 
      Terraform v0.11.7
      provider.aws v1.25.0

**Additional context**
N/A

**Comment by jeteon** [comment]
😕 it seems you're not allowed to specify the VPC for the load balancer since I guess it creates its own. My bad.

**Comment by brandoconnor** [comment]
Hmmm are you saying that if a VPC isn't created (outside the default) that the default will be used? I guess I hadn't tried that case. I would think terraform would fail if `vpc_id` isn't provided as it's a required variable.

**Comment by jeteon** [comment]
I thought that it was possible to supply a `vpc_id` for this resource: 
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/7451e341fd4c1fb417d528fd26f1deb4eed1e9a8/alb_w_logs.tf#L1-L27 
but it turns out you can't.

From what I gather from trying this manually via the AWS console, it would infer some VPC from the provided subnets and security group. However, those subnets have to be public ones and I was mistakenly supplying private subnets which for some reason made it try to use the default VPC for that resource so I kept getting this error:

```
* aws_lb.application:  Error creating Application Load Balancer: InvalidConfigurationRequest: Security group 'sg-xxxxxxxx' does not belong to VPC 'vpc-yyyyyyyy'.
```.

At this stage I only know enough about these things to just get by so please forgive me if my confusion led you to believe there was an issue with the module. After correcting my mistake, it seems to work as expected.

**Comment by brandoconnor** [comment]
Thanks for the explanation and no problem. Have a peek at the test fixture code if you need a working example to help get started: https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/alb_test_fixture/main.tf 👍
