### ISSUE TITLE
Support for Redirects and Fixed Responses for Application Load Balancer

### ISSUE THREAD

**Issue by nirpod** [terraform-aws-modules/terraform-aws-alb#75]
AWS announced a new feature: Elastic Load Balancing Announces Support for Redirects and Fixed Responses for Application Load Balancer.
link: 
https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/

any idea when this is going to supported in terraform?

**Comment by RSabounds** [comment]
this is an excellent feature that would be good to implement sooner rather than later.

**Comment by brandoconnor** [comment]
That's a question for the upstream provider. [This is the current issue for it.](https://github.com/terraform-providers/terraform-provider-aws/issues/5344) Feel free to reopen this issue when that change lands in a provider release.

**Comment by brandoconnor** [comment]
Thanks btw for keeping an eye on the upstream changes and opening this issue. We'll roll it in as soon as it's available. 👍

**Comment by mbarrien** [comment]
https://github.com/terraform-providers/terraform-provider-aws/issues/5344 has landed and is released in 1.33.0. Time to reopen?

**Comment by kuritonasu** [comment]
> [terraform-providers/terraform-provider-aws#5344](https://github.com/terraform-providers/terraform-provider-aws/issues/5344) has landed and is released in 1.33.0. Time to reopen?

Pinging @nirpod & @brandoconnor !

**Comment by okonon** [comment]
@brandoconnor has this been considered again ?
