### ISSUE TITLE
ALB outputs reference invalid resource attributes

### ISSUE THREAD

**Issue by evan-ravenelle** [terraform-aws-modules/terraform-aws-alb#76]
**Describe the bug**
The module throws an error when I add HTTPS listeners due to invalid attributes in the `aws_lb_listener` resource.

**To Reproduce**
Try to create an ALB with an HTTPS listener.

**Expected behavior**
An ALB is created with an HTTPS listener attached

**Desktop (please complete the following information):**
 - OS: Mac OSX High Sierra
 - Versions 
    - Terraform v0.11.7

**Additional context**
    Error: Error running plan: 2 error(s) occurred:

    * module.app-alb.output.https_listener_arns: Resource 'aws_lb_listener.frontend_https' does not have attribute 'arn' for variable 'aws_lb_listener.frontend_https.*.arn'
    * module.app-alb.output.https_listener_ids: Resource 'aws_lb_listener.frontend_https' does not have attribute 'id' for variable 'aws_lb_listener.frontend_https.*.id'`

**Comment by brandoconnor** [comment]
Hey @evan-ravenelle -

Can you show some source code that produces this error? It looks like you're not creating the `https` resources at all by the output.
