### ISSUE TITLE
Variable to enable creation of alb resources

### ISSUE THREAD

**Issue by kinghuang** [terraform-aws-modules/terraform-aws-alb#77]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the `terraform-aws-alb` in a conditional fashion. In my configuration, I only want to create an ALB in certain cases. Unfortunately, Terraform doesn't support the count parameter for modules (hashicorp/terraform#953), and there's no variable in this module to control whether it creates resources or not.

**Describe the solution you'd like**

The `terraform-aws-vpc` module has a variable named `create_vpc` that controls whether or not it creates actually creates VPC resources. I'd like something similar (e.g., `create_alb`) in this module.

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/variables.tf#L1

**Describe alternatives you've considered**

I couldn't find any alternative ways to conditionally enable/disable this module.

**Additional context**

None.

**Comment by brandoconnor** [comment]
Hi @kinghuang -

Thanks for the issue submission. Are you able to make the PR for this feature. I'm onboard with mirroring how the VPC module does it.

**Comment by kinghuang** [comment]
Sure, I'll take a stab at it and make a PR.
