### ISSUE TITLE
Enabling Logs to S3 backup for existing LB

### ISSUE THREAD

**Issue by sppwf** [terraform-aws-modules/terraform-aws-alb#90]
**Is your feature request related to a problem? Please describe.**
I was thinking to use the module, however I run into a problem.
If I want to enable Logs to be sent to an S3 buckt, LB will be recreated. 

**Describe the solution you'd like**
For production usage, LB recreation that means chaning DNS name and downtime are not good at all.

**Describe alternatives you've considered**
Do not have alternative here.

**Additional context**
N/A

**Comment by brandoconnor** [comment]
Hey @sppwf -

Thankfully, the feature you're after is already supported. The `logging_enabled`,`log_bucket_name`, and `log_location_prefix` control logging to S3. Call the module with the following attributes to enable logging to S3:

```hcl
module "alb" {
  source                        = "terraform-aws-modules/alb/aws"
  logging_enabled          = true
  load_balancer_name            = "my-alb"
  security_groups               = ["sg-edcd9784", "sg-edcd9785"]
  log_bucket_name               = "logs-us-east-2-123456789012"
  log_location_prefix           = "my-alb-logs"
  subnets                       = ["subnet-abcde012", "subnet-bcde012a"]
  tags                          = "${map("Environment", "test")}"
  vpc_id                        = "vpc-abcde012"
  https_listeners               = "${list(map("certificate_arn", "arn:aws:iam::123456789012:server-certificate/test_cert-123456789012", "port", 443))}"
  https_listeners_count         = "1"
  http_tcp_listeners            = "${list(map("port", "80", "protocol", "HTTP"))}"
  http_tcp_listeners_count      = "1"
  target_groups                 = "${list(map("name", "foo", "backend_protocol", "HTTP", "backend_port", "80"))}"
  target_groups_count           = "1"
}

```

**Comment by sppwf** [comment]
Hi,

The idea is that if you add the section for an ALB already created with the same module, ALB will be recreated.
Cannot use the module in this cae :(

**Comment by brandoconnor** [comment]
It's currently not impossible to deliver the feature you're asking for with terraform in its current state. The block that determines S3 logging either has to exist populated or not exist at all to create a healthy load balancer. So the module here is unable to offer just a single resource for the load balancer which is able to switch and play both roles. Creating null attribute blocks is supposed to be supported in version 0.12.x and beyond so perhaps in the future this can be offered.

That said, there's often a way around these problems... If you were able, you could instantiate the ALB (through terraform) with logging alongside the existing load balancer.In this case, the same target groups should be attached so really the only thing to do is to cut over traffic using DNS. When you decide the time is right, you can drain the remaining connections to the non-logging LB and destroy just that resource.
