### ISSUE TITLE
Default security group

### ISSUE THREAD

**Issue by evanstachowiak** [terraform-aws-modules/terraform-aws-alb#92]
Would you consider adding a default security group for the alb? I would think almost any app using this module would need a security group declared to actually use the alb. I'm happy to make a pull request.

**Comment by antonbabenko** [comment]
Security group should not be created by this module, see this code example:

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/aaa2ff19c7f5df0f4f114696d722c336ae1f85e0/examples/complete-alb/main.tf#L28-L39
