### ISSUE TITLE
How can both modules be instantiated in the same state?

### ISSUE THREAD

**Issue by DharmSonariya** [terraform-aws-modules/terraform-aws-alb#95]
I have set up with the terragrunt and I am following instructions from terraform-aws-alb/main.tf . So how I can manage the autoscaling module and the terraform-aws-alb module are instantiated in the same state?
I have tried with *.auto.tfvars as well as with 

terragrunt = {
terraform {
    source = [
source = "git::git@github.com:terraform-aws-modules/terraform-aws-alb.git"
"git::git@github.com:terraform-aws-modules/terraform-aws-autoscaling.git?ref=v2.9.1"
]
  }

but no luck yet.

**Comment by antonbabenko** [comment]
You need to either combine this two module in one infrastructure module and call it.

Or use this to call modules separately:
```
terragrunt = {
  terraform {
    source = "git::git@github.com:terraform-aws-modules/terraform-aws-alb.git"
  }
}
```

Terragrunt can't call several modules as you wanted it.

**Comment by DharmSonariya** [comment]
@antonbabenko I really appreciate your help! is it possible to call modules separately in the same terraform.tfvars file? as far as I am not able to do.

**Comment by antonbabenko** [comment]
No, you can't do it in one file.

**Comment by DharmSonariya** [comment]
@antonbabenko Thank you very much, now I am getting an error when combining both modules. Variable "tags" is a list in "terraform-aws-autoscaling" and a map in "terraform-aws-alb" module. still, conflict is unresolved.

**Comment by antonbabenko** [comment]
In pseudo-code it looks like this:
```
# Content of modules/combined-alb-autoscaling/main.tf
module "alb" {
  source = "git::git@github.com:terraform-aws-modules/terraform-aws-alb.git"
  # ...
  tags = "${var.tags_for_alb}"
}

module "autoscaling" {
  source = "git::git@github.com:terraform-aws-modules/terraform-aws-autoscaling.git"
  # ...
  tags = "${var.tags_for_autoscaling}"
}
```

And then invoke this module as a single infrastructure module:
```
terragrunt = {
  terraform {
    source = "../modules/combined-alb-autoscaling"
  }
}

tags_for_autoscaling = ...
tags_for_alb = ...
```

**Comment by DharmSonariya** [comment]
Thank you for your support. I greatly appreciate your help.
