### ISSUE TITLE
Not possible to use a lambda target group?

### ISSUE THREAD

**Issue by invertigo** [terraform-aws-modules/terraform-aws-alb#96]
**Describe the bug**
Attempting to use a lambda function for the target group of an ALB, I get various errors.  Documentation does not have a clear example of how to implement this functionality, if it is supported at all.

**To Reproduce**
1. Create a lambda function "foo"
2. Attempt to use a target group of type "LAMBDA":
>    module "alb" {
>        [...omitted for brevity...]
>        target_groups = [ {
>            name = "test"
>            backend_protocol = "LAMBDA"
>            backend_port = "3000"
>        } ]
>        target_groups_count = "1"
>    }

3. Run `terraform apply`

**Expected behavior**
Creates an ALB resource with a lambda target group available for attaching functions

**Actual behavior**

Error: module.provider-console_lb.aws_lb_target_group.main_no_logs: expected health_check.0.protocol to be one of [HTTP HTTPS TCP], got LAMBDA

Error: module.provider-console_lb.aws_lb_target_group.main_no_logs: expected protocol to be one of [HTTP HTTPS TCP TLS], got LAMBDA

**Additional context**
Lambda target groups have been supported by the AWS provider since version 1.53.  When specifying a lambda target group, the `backend_port` parameter is not required, but omitting it with this module also causes an error.

**Comment by antonbabenko** [comment]
[v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) has been just released where Lambda functions are supported as target group type.

You can see in `examples/complete-alb` how to create a target group for `lambda`:

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/aaa2ff19c7f5df0f4f114696d722c336ae1f85e0/examples/complete-alb/main.tf#L114-L118

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.
