### ISSUE TITLE
After apply, it deleted my vpc

### ISSUE THREAD

**Issue by omahonyb** [terraform-aws-modules/terraform-aws-alb#99]
**Describe the bug**
Usedthe module to create an ALB. I used a previous module state as a data source. ALB gets created.
When it times out due to provisioning [no tgs currently], it eventually went and deleted my whole vpc!

**Expected behavior**
If the ALB times out, dont go delete the vpc

**Desktop (please complete the following information):**
MAC, TF 0.11.13, AWS-CLI 1.16.140

**Additional context**
I created a vpc using the official TF vpc module, but stripped the SG and Routes out for my own reasons.
I used the tfstate that was outputted to S3 for some vars for the ALB.
I manually entered the default SG.

**Comment by omahonyb** [comment]
Same result for logs or no logs

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  + module.alb.aws_lb.application_no_logs
      id:                         <computed>
      access_logs.#:              <computed>
      arn:                        <computed>
      arn_suffix:                 <computed>
      dns_name:                   <computed>
      enable_deletion_protection: "true"
      enable_http2:               "true"
      idle_timeout:               "60"
      internal:                   "false"
      ip_address_type:            "ipv4"
      load_balancer_type:         "application"
      name:                       "web-alb-tmo-dev"
      security_groups.#:          "1"
      security_groups.3803735186: "sg-0b4f65678e77eefd3"
      subnet_mapping.#:           <computed>
      subnets.#:                  "3"
      subnets.1017906531:         "subnet-07110aaff57850aea"
      subnets.3051565764:         "subnet-06c3a3f47b4464305"
      subnets.3922050942:         "subnet-07e79bf57be2aceef"
      tags.%:                     "5"
      tags.Environment:           "test"
      tags.GithubOrg:             "terraform-aws-modules"
      tags.GithubRepo:            "tf-aws-alb"
      tags.Name:                  "web-alb-tmo-dev"
      tags.Workspace:             "default"
      vpc_id:                     <computed>
      zone_id:                    <computed>
  - module.vpc.aws_eip.nat[0]

  - module.vpc.aws_eip.nat[1]

  - module.vpc.aws_eip.nat[2]

  - module.vpc.aws_vpc.this

**Comment by lsc** [comment]
Did you create the ALB and VPC in the same state / module? 
If you did, that's expected behaviour, and has nothing to do with this module, but rather on how Terraform and basic level works.

**Comment by omahonyb** [comment]
I honestly dont think so. Closing ticket - I was getting used to TF and have way more practise now - i had forgotten about this ticket it was so long ago.
